#!/bin/bash

export PROC=battleship
export CMD=battleship
DEBUG=0
STATIC=0

function help {
  echo "Usage: `basename $0` [ --static ] [ --debug ] [ <battleship_args> ]" 1>&2
}

while [ "$1" != "" ] ; do
  case $1 in
    "-h"|"--help")
      help
      ./${CMD} -h
      exit 1
    ;;
    "--debug")
      DEBUG=1
      shift
    ;;
    "--static")
      STATIC=1
      shift
    ;;
    *)
      break
    ;;
  esac
done


if [ $STATIC -eq 1 ] ; then
  export PROC=battleship_stat
  export CMD=battleship.stat
fi

if [ $DEBUG -eq 1 ] ; then
  export ${PROC}_TRACE_Communication='Debug'
  export ${PROC}_TRACE_SetuAp='Debug'
  export ${PROC}_TRACE_Play='Debug'
  export ${PROC}_TRACE_Autobus='Debug+'
fi
# export TCP_UTIL_DEBUG_RECEPTION=Y
exec ./${CMD} 234.7.6.5:21210 $*

