#!/bin/bash
DEBUG=0
if [ $DEBUG -eq 1 ] ; then
  export battleship_TRACE_Communication='Debug'
  export battleship_TRACE_SetuAp='Debug'
  export battleship_TRACE_Play='Debug'
  export battleship_TRACE_Autobus='Debug+'
fi
# export TCP_UTIL_DEBUG_RECEPTION=Y
exec ./battleship 234.7.6.5:21210 $*

