include $(HOME)/Makefiles/common.mk

ADAVIEW := $(REPOSIT)

AFPX := true
AFPX_XREF := afpx_xref

EXES := battleship

CLIBS :=  posix2pcre pcre x_mng cutil X11

TXT := BattleShip
DOCOPTS_Asubst := -a toc

include $(TEMPLATES)/ada.mk

