#!/bin/bash
if [ -n "$1" ] ; then
  export PROG="$*"
else
  export PROG="./Test"
fi

res=0
let n=0+1
while [ $res -eq 0 ] ; do
  echo `date +"%Y-%m-%dT%H:%M:%S"`" Iteration "$n":"
  $PROG
  if [ $? -ne 0 ] ; then
    echo "Failed!"
    exit 1
  fi
  let n=$n+1
done

