#!/bin/bash

export ORIG=$PWD
trap 'echo "Test cleaning"; cd $ORIG; ./Test clean; \
      echo Test aborted; exit 0' SIGINT SIGTERM

T0=`date "+%s"`
case "$1" in
  "")
    make test
  ;;
  "clean")
    make clean_test
  ;;
  *)
    echo "Unknown command $1"
    exit 1
  ;;
esac

T1=`date "+%s"`
echo $T0 $T1 | awk '
  {D=$2-$1
   printf "Done in %dmn%ds\n", D/60, D%60
  }
'

