#!/bin/bash

export ORIG=$PWD
trap 'echo "Test cleaning"; cd $ORIG; ./Test clean; \
      echo Test aborted; exit 0' SIGINT SIGTERM

T0=`date "+%s"`
for file in `find .  -name "Test" | sort` ; do
  export dir=`dirname $file`
  if [ "$1" != "clean" ] ; then
    echo "`basename $dir`:"
  fi
  cd "$dir"
  ./Test $*
  if [ "$?" -ne 0 ] ; then
    echo "ERROR."
    exit 1
  fi
  if [ "$1" != "clean" ] ; then
    echo ""
  fi
  cd $ORIG
done
T1=`date "+%s"`
echo $T0 $T1 | awk '
  {D=$2-$1
   printf "Done in %dmn%ds\n", D/60, D%60
  }
'

