#!/bin/bash
export ORIG=$PWD
for file in */Test ; do
  export dir=`dirname $file`
  echo "`basename $dir`:"
  cd "$dir"
  ./Test
  if [ "$?" -ne 0 ] ; then
    echo "ERROR."
    exit 1
  fi
  echo ""
  cd $ORIG
done
echo "OK."

