#!/bin/bash
export ORIG=$PWD
T0=`date "+%s"`
for file in */Test ; do
  export dir=`dirname $file`
  echo "`basename $dir`:"
  cd "$dir"
  ./Test $*
  if [ "$?" -ne 0 ] ; then
    echo "ERROR."
    exit 1
  fi
  echo ""
  cd $ORIG
done
T1=`date "+%s"`
echo $T0 $T1 | awk '
  {D=$2-$1
   printf "Done in %dmn%ds\n", D/60, D%60
  }
'

