#!/bin/bash
if [ "$1" = "-h" ] ; then
  echo "Usage: `basename $0` [ <date> ]"
  echo "<date> ::= dd/mm/YYyy"
  exit 1
fi
export ENIGMA_CONF_FILE=${HOME}/ada/usr/enigma/enigma.cnf
exec enigma `def_enigma $*`

