#!/bin/bash
if [ "$1" = "-h" ] ; then
  echo "Usage: `basename $0` [ <def_enigma_args> ]" 1>&2
  echo "<date> ::= dd/mm/YYyy" 1>&2
  exit 1
fi
export ENIGMA_CONF_FILE=${HOME}/ada/usr/enigma/enigma.cnf
exec enigma `def_enigma $*`

