include $(HOME)/Makefiles/common.mk

ADAVIEW := $(REPOSIT)
ADAWARN := true
EXES := anal_freq enigma scrambler_generator def_enigma letterator

CLIBS := cutil
CLIBS_enigma := posix2pcre pcre
CLIBS_def_enigma := posix2pcre pcre

include $(TEMPLATES)/ada.mk

