#!/bin/bash

# Test dir
export TDIR=test

# Report an error
function error {
  echo "ERROR: $1." 1>&2
  exit 1
}

# Check that $2 = $3
# if $1 is -d then compare floats modulo Espilon
# Echo 0 if OK and 1 otherwise
function check {
  if [ "$1" = "-d" ] ; then
    echo $2 | awk -v EXPECT="$3" -v EPS="1.0E-7" '
    function abs(v) {return v < 0 ? -v : v}
    {
      NEXPECT=split(EXPECT, EXPECTS)
      NOUTPUT=split($0, OUTPUTS);
      if (NEXPECT != NOUTPUT) {print "1"; exit}
      for (i = 1; i < NEXPECT+1; i++) {
        E = 0.0+EXPECTS[i]
        O = 0.0+OUTPUTS[i]
        D = abs(E - O)
        if (D > EPS) {
          if (E < 0.0) E += 360.0
          if (O < 0.0) O += 360.0
          D = abs(E - O)
          if (D > EPS) {
            print "1"
          }
        }
      }
      print "0"
    }
    '
  else
    if [ "$2" = "$3" ] ; then
      echo 0
    else
      echo 1
    fi
  fi
}

# Encode
echo Encode
# For each line, read code precision lat lon precision code
while IFS=' ' read -r lat lon prec code ; do
  if [[ $lat =~ ^#|^$ ]] ; then
    continue
  fi
  # Encode
  result=`t_olc -c $lat $lon $prec`
  if [ $? -ne 0 ] ; then
    error "t_olc -c $lat $lon $prec has failed"
  fi
  # Parse result: Code
  if [ "$result" != "$code" ] ; then
    error "t_olc -c $lat $lon $prec returned $result instead of $code"
  fi
  echo "t_olc -c $lat $lon $prec => $result"
done <$TDIR/Encode

# Decode
echo Decode
# For each line, read code precision lat1 lon1 lat2 lon2
while IFS=' ' read -r code prec lat1 lon1 lat2 lon2  ; do
  if [[ $code =~ ^#|^$ ]] ; then
    continue
  fi
  # Decode
  result=`t_olc -d $code`
  if [ $? -ne 0 ] ; then
    error "t_olc -d $code has failed"
  fi
  # Parse result: lat1 lon1 lat 2 lon2
  res=`check "-d" "$result"  "$lat1 $lon1 $lat2 $lon2"`
  if [ "$res" != "0" ] ; then
    error "t_olc -d $code => $result instead of $lat1 $lon1 $lat2 $lon2"
  fi
  echo "t_olc -d $code => $lat1 $lon1 $lat 2 $lon2"
done <$TDIR/Decode
echo OK.

# Size and Full status
echo Size
# For each line, read code precision
while IFS=' ' read -r code prec tail ; do
  if [[ $code =~ ^#|^$ ]] ; then
    continue
  fi
  # Get status
  result=`t_olc -S $code`
  if [ $? -ne 0 ] ; then
    error "t_olc -S $code has failed"
  fi
  # Parse result: precision status
  res=`check "-s" "$result"  "$prec Full"`
  if [ "$res" != "0" ] ; then
    error "t_olc -s $code => $result instead of $prec Full"
  fi
  echo "t_olc -S $code => $prec Full"
done <$TDIR/Decode
echo OK.

# Various status 
echo Status
# For each line, read code and status ((2 fields max)
while IFS=' ' read -r code stat1 stat2 ; do
  if [[ $code =~ ^#|^$ ]] ; then
    continue
  fi
  # Get status
  result=`t_olc -S $code`
  if [ $? -ne 0 ] ; then
    error "t_olc -S $code has failed"
  fi
  # Parse result: status
  if [ "$stat1" = "Invalid" ] ; then
    res=`check "-s" "$result"  "$stat1"`
  else
    res=`check "-s" "$result"  "$stat1 $stat2"`
  fi
  if [ "$res" != "0" ] ; then
    error "t_olc -S $code => $result instead of $stat1 $stat2"
  fi
  echo "t_olc -S $code => $stat1 $stat2"
done <$TDIR/Status
echo OK.

# Short
echo Short
# For each line, read code lat, Lon Short and Kind (R, S or B)
while IFS=' ' read -r code lat lon short kind ; do
  if [[ $code =~ ^#|^$ ]] ; then
    continue
  fi
  # Test shorten
  if [ \( "$kind" = "S" \) -o \( "$kind" = "B" \) ] ; then
    result=`t_olc -s $code $lat $lon`
    if [ $? -ne 0 ] ; then
      error "t_olc -s $code $lat $lon has failed"
    fi
    # Parse result: short
    res=`check "-s" "$result" "$short"`
    if [ "$res" != "0" ] ; then
      error "t_olc -s $code $lat $lon => $result instead of $short"
    fi
    echo "t_olc -s $code $lat $lon => $short"
  fi
  # Test nearest
  if [ \( "$kind" = "R" \) -o \( "$kind" = "B" \) ] ; then
    result=`t_olc -n $short $lat $lon`
    if [ $? -ne 0 ] ; then
      error "t_olc -n $short $lat $lon has failed"
    fi
    # Parse result: full code
    res=`check "-s" "$result" "$code"`
    if [ "$res" != "0" ] ; then
      error "t_olc -n $short $lat $lon => $result instead of $code"
    fi
    echo "t_olc -n $short $lat $lon => $short"
  fi
done <$TDIR/Short 
echo OK.


