include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk
SUBDIRS := battleship chess fourtwentyone freecell klondike lapeau lem mmind \
  nimmari renardeau sokoban


include $(TEMPLATES)/dir.mk

