#!/bin/bash
export X_FONT_6="-adobe-courier-medium-r-normal--17-120-100-100-m-0-iso10646-*"
export X_FONT_7="-adobe-courier-bold-r-normal--17-120-100-100-m-0-iso10646-*"
chess -S -cwhite -p50000 $CHESS_OPTIONS $* &
chess -C -cblack -slocalhost -p50000 $CHESS_OPTIONS $* &
