#!/bin/bash
if [ "$1" = "html" ] ; then
  gnathtml.pl -D -o html */*.ad? */*/*.ad?
  exit 0
elif [ "$1" = "clean_html" ] ; then
  rm -rf html/*
  exit 0
fi

cur=`pwd`

cd c
make $*
cd $cur

cd reposit
make $*
cd $cur

cd usr
build $*
cd $cur

