#!/bin/bash
if [ "$1" = "html" ] ; then
  gnathtml -D -o html */*.ad? */*/*.ad?
  exit 0
elif [ "$1" = "clean_html" ] ; then
  rm -rf html/*
  exit 0
elif [ "$1" = "clean_all" ] ; then
  build clean
  build clean_exe
  build clean_html
  exit 0
elif [ "$1" = "all" ] ; then
  build
  build html
  exit 0
elif [ "$1" = "help" ] ; then
  echo "Usage: `basename $0`  [ html | clean_html | all | clean_all ] "
  exit 0
fi

cur=`pwd`

cd c
make $*
cd $cur

cd reposit
make $*
cd $cur

cd usr
build $*
cd $cur

