#!/bin/bash
# gnatmake, gnatstub and gnatls
# Only "-noview" for gnatls is handled here
#  other args are passed
if [ -z "$GNATPATH" ] ; then
  export GNATPATH="/usr/bin"
fi

# Like makefiles
export HOST=`uname -s`
export LIB=lib_$HOST

# Function to guess ADAVIEW if necessary and possible
function guessview {
  MAKEFILE=""
  if [ -z "$ADAVIEW" ] ; then
    if [ -f makefile ] ; then
      MAKEFILE=makefile
    fi
    if [ -f Makefile ] ; then
      MAKEFILE=Makefile
    fi
  fi
  res=1
  if [ -n "$MAKEFILE" ] ; then
    grep ADAVIEW $MAKEFILE >/dev/null 2>&1
    res=$?
  fi
  if [ $res -eq 0 ] ; then
    export ADAVIEW=`make --no-print-directory echoadaview 2>/dev/null`
    if [ $? -ne 0 ] ; then
      export ADAVIEW=""
    fi
  fi
}

# Function to make flags from ADAVIEW
function mkflags {
  if [ "$ADAVIEW" = "-" ] ; then
    return
  fi
  for view in $ADAVIEW; do
    GNATFLAGS=$GNATFLAGS" $1$view/$2"
  done
}

# Default behaviour
export COMMAND=`basename $0`
guessview
export GNATFLAGS=""
mkflags -aI
mkflags -aO $LIB

# Modif from default
if [ "$COMMAND" = "ada" ] ; then
  # Specific mapping ada -> gcc
  export COMMAND="gcc -c"
  export GNATFLAGS="-gnat2012"
  mkflags -I
  exec $COMMAND $GNATFLAGS $ADAOPT $ADAFLAGS $* $POSTARGS
  exit 0
fi
if [ "$COMMAND" = "gnatls" ] ; then
  if [ "$1" = "-noview" ] ; then
    export ADAVIEW=""
    export GNATFLAGS=""
    shift
  else
    guessview
  fi
  if [ -d $LIB ] ; then
    export GNATFLAGS="-I$LIB $GNATFLAGS" 
  fi
fi

exec $GNATPATH/$COMMAND$GNAT_SUFFIX $GNATFLAGS $ADAOPT $ADAFLAGS $* $POSTARGS

