include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk
include $(TEMPLATES)/units.mk

ADAVIEW := $(REPOSIT)
ADACTL := true

EXES := lapeau

CLIBS := cards $(X11_SLIBS) Xext

include $(TEMPLATES)/ada.mk

