#!/bin/bash
export FILE=code.adb
export TMP=tmpfile
export PASSWD=Melusine

function compare {
  echo Comparing
  cmp -s $TMP.ini $TMP.dec
  if [ $? -eq 0 ] ; then
    echo "Test OK."
    echo ""
    rm -f $TMP.cod $TMP.dec $TMP.ini
  else
    echo "Test is not OK. Please check the files."
    exit 1
  fi
}

echo "Testing CODE"
cp $FILE $TMP.ini
echo "Coding"
echo "$PASSWD" | code -c $TMP.ini $TMP.cod
echo "Decoding"
echo "$PASSWD" | code -d $TMP.cod $TMP.dec
compare

echo "Testing VIGENERE"
# Letters -> UPPERCASE, others -> ' '
cat $FILE | asubst -D '' '([A-Za-z])|(.|\n)' '\i11\u\r11\c\i12 \f' > $TMP.ini
echo "Coding"
cat $TMP.ini | t_vigenere -c "$PASSWD" > $TMP.cod
echo "Decoding"
cat $TMP.cod | t_vigenere -d "$PASSWD" > $TMP.dec
compare

