# For Mine Detector 6.0
include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAWARN := false

EXES := mine_detector

OPTIMIZED := mine_detector field field-operations user_if
GARGS := `gtkada-config`


TXT := Readme

include $(TEMPLATES)/ada.mk

