include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(REPOSIT)
ADACTL := true

EXES := tcpipe

CLIBS := $(UTILS_SLIBS)

TXT := Tcpipe

include $(TEMPLATES)/ada.mk

