#!/bin/bash
if [ -z "$1" ] ; then
  echo "USAGE: `basename $0` <command_file> [ { <arg> } ]" >&2
  exit 1
fi
file=$1
shift
if [ -z "$*" ] ; then
  exec mmcdt -e $file
else
  exec mmcdt "$*" -e $file
fi

