#!/bin/bash

if [ \( $# -eq 1 \) -a \( "$1" = "-h" \) ] ; then
  echo "USAGE: `basename $0` { [ { <arg> } ] -e <command_file> }" >&2
  exit 1
fi

com=/tmp/.mmcdt.mcd
if [ -f $com ] ; then
  rm -f $com
  if [ -f $com ] ; then
    echo "Error. Cannot remove tmp file $com" >&2
    exit 2
  fi
fi

touch $com
if [ ! -f $com ] ; then
  echo "Error. Cannot create tmp file $com" >&2
  exit 2
fi

while [ $# -ne 0 ] ; do
  if [ "$1" = "-e" ] ; then

    if [ ! -f "$2" ] ; then
      echo "Error. File "$2" not found." >&2
      exit 3
    fi
    cat "$2" >> $com
    shift; shift
  elif [ ! -z "$1" ] ; then
    echo "$1" >> $com
    shift
  else
    shift
  fi
done

mcd < $com
res=$?
rm -f $com
exit $res

