#!/bin/bash
error() {
  echo "Usage: $1 <num1> <oper> <num2>"
  echo " <oper> ::= + | - | * | /"
  echo " <num1> is in Hours.MinutesSecondsMiliseconds"
  echo " <num2> is in Hours.MinutesSecondsMiliseconds if <oper> is + or -"
  exit 1
}

if [ $# -ne 3 ] ; then
  error `basename $0`
fi
case "$2" in
  "+" | "-" )
    num2="$3 toreal msd"
  ;;
  "*" | "/" )
    num2="$3 toreal"
  ;;
  * )
    error `basename $0`
esac
 
mmcdt "$1" toreal msd "$num2" "$2" -e op_time.mcd 

