with Normal, Rnd, Argument, Basic_Proc;
procedure Generate is
  Dim : Positive;
begin

  if Argument.Get_Nbre_Arg /= 1 then
    return;
  end if;

  begin
    Dim := Positive'Value(Argument.Get_Parameter);
  exception
    when others =>
      return;
  end;

  Rnd.Randomize;
  Basic_Proc.Put_Line_Output ("# Generated by " & Argument.Get_Program_Name);
  if Rnd.Int_Random = 0 then
    Basic_Proc.Put_Line_Output ("REGRET");
  else
    Basic_Proc.Put_Line_Output ("WISH");
  end if;

  for I in 1 .. Dim loop
    for J in 1 .. Dim loop
      Basic_Proc.Put_Output (Normal(Rnd.Int_Random(0, 100), 3) & " ");
    end loop;
    Basic_Proc.New_Line_Output;
  end loop;

end Generate;

