with Ada.Text_Io;
with Normal, Rnd, Argument;
procedure Generate is
  Dim : Positive;
  File : Ada.Text_Io.File_Type;
begin

  if Argument.Get_Nbre_Arg /= 1 then
    return;
  end if;

  begin
    Dim := Positive'Value(Argument.Get_Parameter);
  exception
    when others =>
      return;
  end;

  Rnd.Randomize;
  Ada.Text_Io.Put_Line ("# Generated by " & Argument.Get_Program_Name);
  if Rnd.Int_Random = 0 then
    Ada.Text_Io.Put_Line ("REGRET");
  else
    Ada.Text_Io.Put_Line ("WISH");
  end if;

  for I in 1 .. Dim loop
    for J in 1 .. Dim loop
      Ada.Text_Io.Put (Normal(Rnd.Int_Random(0, 100), 3) & " ");
    end loop;
    Ada.Text_Io.New_Line;
  end loop;

end Generate;

