#!/bin/bash
if [ "$1" = "clean" ]  ; then
  exit 0
fi

export FILES="$*"
if [ "$FILES" = "" ] ; then
  FILES="test*.dat"
fi

echo "Testing hungar"
for file in $FILES; do
  echo -n $file
  if [ $file = test60.dat ] ; then
    export MAX_LOOPS=--max
  else
    export MAX_LOOPS=""
  fi
  hungar $MAX_LOOPS $file >/dev/null
  res=$?
  if [ $res -eq 0 ] ; then
    echo " OK"
  elif [ $res -eq 2 ] ; then
    echo " => Not found" 
  elif [ $res -ne 0 ] ; then
    echo ""
    echo "ERROR." 2>&1
    exit $res
  fi
done
echo "Test OK."
echo
