include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(REPOSIT)

AFPX := true
AFPX_XREF := afpx_xref

EXES := xwords words_check t_analist

CLIBS_xwords := $(X11_SLIBS)
CLIBS := $(UTILS_SLIBS)

include $(TEMPLATES)/ada.mk

