include $(HOME)/Makefiles/common.mk

ADAVIEW := $(REPOSIT)
AFPX := true
EXES := xwords words_check t_file_hash t_analist

CLIBS_xwords := x_mng cutil X11
CLIBS_words_check := cutil
CLIBS_t_file_hash := cutil

include $(TEMPLATES)/ada.mk

