include $(HOME)/Makefiles/common.mk

ADAVIEW := $(REPOSIT)
ADAWARN := true
AFPX := true
EXES := xwords words_check

CLIBS_xwords := x_mng cutil X11
CLIBS_words_check := cutil

include $(TEMPLATES)/ada.mk

