#!/bin/bash
export WORDS_PATH=${HOME}/words
export DICTIO_WORDS_FILE=${WORDS_PATH}/french_words
export DICTIO_NOUNS_FILE=${WORDS_PATH}/french_nouns
export XWORDS_DIR=${HOME}/ada/usr/xwords
export AFPX_DATA_DIR=${XWORDS_DIR}

${XWORDS_DIR}/xwords $*

