-- Tranformation between C_Types.Timeval and Perpet.Delta_Rec
with Perpet, C_Types;
package Timeval is

  -- Not generated by conversion from Perpet.Delta_Rec
  --  but this is a conventional value of timeval in C so it
  --  handled by Image
  Infinite_C_Timeout : constant C_Types.Timeval_T := (-1, -1);

  -- Convert a Perpet.Delta_Rec into Timeval
  function To_C_Timeout (Delta_Date : Perpet.Delta_Rec)
                        return C_Types.Timeval_T;

  -- Convert a Timeval into Perpet.Delta_Rec
  function To_Delta (Timeout : C_Types.Timeval_T) return Perpet.Delta_Rec;

  -- Image of a Timeval
  function Image (Timeout : C_Types.Timeval_T) return String;

  -- If overflow on Tv_Sec in To_C_Timeout
  -- If Timeout of To_Delta is < 0
  Timeval_Error : exception;
end Timeval;

