include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(USR)/fifos $(USR)/dictio $(REPOSIT)
ADACTL := true

EXES := pipe

CLIBS := $(UTILS_SLIBS)

include $(TEMPLATES)/ada.mk

