include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(REPOSIT)

EXES := tcpchat tios

CLIBS := cutil posix2pcre $(PCRE_LIBS)

TXT := Tcpchat
DOCOPTS_Tcpchat := -a toc

include $(TEMPLATES)/ada.mk

