#!/bin/bash
# Automatic test of Tcpchat

export VERS="V2.1"

export DBG=1

if [ $DBG -eq 1 ] ; then
  export TCPCHAT_DEBUG=Y
  export DEBUG=debug
else
  export DEBUG=/dev/null
fi

# Prepare env
export SPACE='µ'
export NONE='£'
export HOSTNAME
export PASSWORD="userpass"
export PIPE=pipe
export RES=result
export EXPECTED=expected
if [ ! -p $PIPE ] ; then
  mknod $PIPE p
fi

# Send text (on the pipe) / and sleep...
function send {
  sleep 1
  while [ "$1" != "" ] ; do
    str="`echo -e "$1" | asubst ${SPACE} ' '`"
    if [ "$str" = "${NONE}" ] ; then
      str=""
    fi
    echo -e "$str"
    shift
    if [ "$1" = "" ] ; then
      return
    fi
    sleep $1
    shift
  done
}

# Clean
function clean {
  rm $PIPE
}

# A test.
# $1 is the file with expected result
# Other args are series of sentences to send and delay to wait
function try {
  local expected="$1"
  shift

  # Start tcpchat
  tcpchat -p - -f chats.xml <$PIPE >$RES 2>$DEBUG &
  PID=$!

  # Send stimulus and stop
  send $@ > $PIPE
  kill $PID
  sleep 1

  # Compare with expected
  cmp -s $RES "$expected"
  if [ $? -ne 0 ] ; then
    echo "ERROR: Result $RES differs from expected $expected" 2>&1
    clean
    exit 1
  else
    echo "OK"
  fi
  rm $RES $EXPECTED
}

# Ping
echo -n "Test ping: "
echo "pong" > $EXPECTED
try $EXPECTED ping 1

# HTTP 0.9 ok
echo -n "Test http 0.9 ok: "
cp chats.xml $EXPECTED
try $EXPECTED "GET${SPACE}http://localhost${PWD}/chats.xml" 1

# HTTP 1.0 ok
# If we are close to the end of the minute, we must wait for next minute
let min=0+`date +%-S`
if [ $min -ge 57 ] ; then
  sleep 5
fi
export SIZE=`ls -al chats.xml | awk '{print $5}'`
export DATE=`date "+%a, %d %b %Y %H:%M:00 %Z"`
echo -n "Test http 1.0 ok: "
echo -en "HTTP/1.0 200 OK\nDate: ${DATE}\nServer: tcpchat/${VERS}\n" > $EXPECTED
echo -en "Connection: close\nAccept-Ranges: bytes\n" >> $EXPECTED
echo -en "Content-Length: ${SIZE}\nContent-Type: text/plain\n\n" >> $EXPECTED
cat chats.xml >> $EXPECTED
try $EXPECTED "GET${SPACE}http://localhost${PWD}/chats.xml${SPACE}HTTP/1.0" 0 "Host:${SPACE}${HOSTNAME}" 0 \
"Connection:${SPACE}close" 0 "${NONE}" 1

# HTTP 0.9 ko
echo -n "Test http 0.9 ko: "
echo -en "" > $EXPECTED
try $EXPECTED "GET${SPACE}http://localhost${PWD}/chats.XML" 1

# HTTP 1.0 ko
echo -n "Test http 1.0 ko: "
echo -en "HTTP/1.0 404 Not Found\n" > $EXPECTED
try $EXPECTED "GET${SPACE}http://localhost${PWD}/chats.XML${SPACE}HTTP/1.0" 0 "${NONE}" 1

# Ppp1 ok
echo -n "Test ppp1 ok: "
echo -en "AT\nATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0\nATDT0860922000\nmalaise\n$PASSWORD\nWorking: Please wait...\nDone. Please logout.\n" > $EXPECTED
try $EXPECTED ppp1 0 OK 0 OK 0 CONNECT${SPACE}56000 0 login 0 password 6 logout

# Ppp1 error
echo -n "Test ppp1 ko: "
echo -en "AT\nATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0\nATDT0860922000\n" > $EXPECTED
try $EXPECTED ppp1 0 OK 0 OK 0 NO${SPACE}DIALTONE

# Ppp2
echo -n "Test ppp2: "
echo -en  "OK\nOK\nCONNECT 56000\nlogin\npassword\nWorking: Please wait...\nDone. Please logout.\n" > $EXPECTED
try $EXPECTED ppp2 0 AT 0 "ATQ0${SPACE}V1${SPACE}E1${SPACE}S0=0${SPACE}&C1${SPACE}&D2${SPACE}+FCLASS=0" 0 ATDT0860922000 32 malaise 0 $PASSWORD 6 logout

# Multi 1
echo -n "Test Multi 1: "
echo -en  "\nme\npass\nls\n" > $EXPECTED
try $EXPECTED testMulti 0 login 0 password 2

# Multi 2
echo -n "Test Multi 2: "
echo -en  "\nme\nPASS\nls\n" > $EXPECTED
try $EXPECTED testMulti 0 login 0 PASSWORD 2

# Multi 3
echo -n "Test Multi 3: "
echo -en  "\nme\n" > $EXPECTED
try $EXPECTED testMulti 0 login 0 Password

# Multi 4
echo -n "Test Multi 4: "
echo -en  "\nME\nPASS\n" > $EXPECTED
try $EXPECTED testMulti 0 LOGIN 0 PASSWORD 2

# Multi 5
echo -n "Test Multi 5: "
echo -en  "\n" > $EXPECTED
try $EXPECTED testMulti 0 Login

# Login OK
echo -n "Test login ok: "
echo -en  "login:\npassword:\nlogin:\npassword:\nUser malaise logged in\nUser malaise logged out\n" > $EXPECTED
try $EXPECTED login 0 user 0 password 0 malaise 0 ${PASSWORD} 3 logout

# Login KO
echo -n "Test login ko: "
echo -en  "login:\npassword:\nlogin:\npassword:\nlogin:\npassword:\nlogin:\npassword:\nlogin:\npassword:\nLogin failed\n" > $EXPECTED
try $EXPECTED login 0 user 0 password 0 user 0 password 0  user 0 password 0 user 0 password 0 user 0 password 1 logout

# Logout KO
echo -n "Test logout ko: "
echo -en  "" > $EXPECTED
try $EXPECTED logout

# Error 1 (nothing after handler)
echo -n "Test error1: "
echo -en  "error-handler-1\n" > $EXPECTED
try $EXPECTED error1

# Error 2 (a send after handler)
echo -n "Test error2: "
echo -en  "error-handler-2\nafter-error-2\n" > $EXPECTED
try $EXPECTED error2

# Clean
clean
if [ $DBG  -eq 1 ] ; then
  rm $DEBUG
fi
echo "Done."

