#!/bin/bash
# Automatic test of Tcpchat

export VERS="V"`tcpchat -v`

export DBG=0
if [ "$1" = "-d" ] ; then
  DBG=1
fi

export DEBUG=debug
if [ $DBG -eq 1 ] ; then
  export tcpchat_TRACE=debug
fi

# Prepare env
export SPACE='µ'
export NONE='£'
export HOSTNAME
export PASSWORD="userpass"
export PIPE=pipe
export RES=result
export EXPECTED=expected
export SLEEPSTART=0.1
export SLEEPEND=0.3
if [ ! -p $PIPE ] ; then
  mknod $PIPE p
fi

# UTILITIES
# ---------
# Clean
function clean {
  rm -f $PIPE $DEBUG $RES $EXPECTED
}
trap 'echo ""; clean; exit 1' SIGINT SIGTERM

if [ "$1" = "clean" ]  ; then
  clean
  exit 0
fi


# Send text $1 (on the pipe) then sleep $2...
# If last arg is a $1 (odd Nb of arg) then sleep a bit before returning
# If called with ... cmd 0 then we add a sleep 1 otherwise tcpchat
#  is likely to die on SIGPIPE before completing the processing
function send {
  sleep 1
  while [ "$1" != "" ] ; do
    str="`echo -e "$1" | asubst ${SPACE} ' '`"
    if [ "$str" = "${NONE}" ] ; then
      str=""
    fi
    echo -e "$str"
    shift
    if [ "$1" = "" ] ; then
      # Wait a bit before returning (which will SIGPIPE tcpchat)
      sleep ${SLEEPEND}
      return
    fi
    sleep $1
    prevsleep=$1
    shift
    if [ \( "$1" = "" \) -a \( "$prevsleep" = "0" \) ] ; then
      # Called with ... cmd 0
      sleep ${SLEEPEND}
    fi
  done
}


# Check that result $1 matches expected $2
function check {
  # Compare with expected
  cmp -s $1 $2
  if [ $? -ne 0 ] ; then
    echo "ERROR: Result $1 differs from expected $2" 1>&2
    exit 1
  else
    rm -f $1 $2
    echo "OK"
  fi
}

# A test.
# $1 is the file with expected result
# Other args are series of sentences to send and delay to wait
#  see function "send"
function try {
  local expected="$1"
  shift

  # Start tcpchat
  tcpchat -p - -f chats.xml <$PIPE >$RES 2>$DEBUG &
  PID=$!
  sleep ${SLEEPSTART}

  # Send stimulus
  send $@ > $PIPE
  # Normally not necessary because tcpchat has got sigpipe at end of send
  kill $PID 2>/dev/null

  # Compare with expected
  check $RES "$expected"
}

# START tests
# -----------

# Command ls and exit of rsh.xml
echo -n "Test rsh: "
touch $RES $EXPECTED $DEBUG
tcpchat -p - -f rsh.xml <$PIPE >$RES 2>$DEBUG &
ls > $EXPECTED
send ls 0 exit 0 >$PIPE
check $RES $EXPECTED

# Various chats of chats.xml
# Ping
echo -n "Test ping: "
echo -n "pong" > $EXPECTED
try $EXPECTED ping

# Tcping
echo -n "Test tcping: "
echo -n "tcpong" > $EXPECTED
try $EXPECTED tcping

# HTTP 0.9 ok
echo -n "Test http 0.9 ok: "
cp chats.xml $EXPECTED
try $EXPECTED "GET${SPACE}http://localhost${PWD}/chats.xml"

# HTTP 1.0 ok
# If we are close to the end of the minute, we must wait for next minute
let min=0+`date +%-S`
if [ $min -ge 57 ] ; then
  sleep 5
fi
export SIZE=`ls -al chats.xml | awk '{print $5}'`
export DATE=`date "+%a, %d %b %Y %H:%M:00 %Z"`
echo -n "Test http 1.0 ok: "
echo -en "HTTP/1.0 200 OK\nDate: ${DATE}\nServer: tcpchat/${VERS}\n" > $EXPECTED
echo -en "Connection: close\nAccept-Ranges: bytes\n" >> $EXPECTED
echo -en "Content-Length: ${SIZE}\nContent-Type: text/plain\n\n" >> $EXPECTED
cat chats.xml >> $EXPECTED
try $EXPECTED "GET${SPACE}http://localhost${PWD}/chats.xml${SPACE}HTTP/1.0" 0 "Host:${SPACE}${HOSTNAME}" 0 \
"Connection:${SPACE}close" 0 "${NONE}"

# HTTP 0.9 ko
echo -n "Test http 0.9 ko: "
echo -en "" > $EXPECTED
try $EXPECTED "GET${SPACE}http://localhost${PWD}/chats.XML"

# HTTP 1.0 ko
echo -n "Test http 1.0 ko: "
echo -en "HTTP/1.0 404 Not Found\n" > $EXPECTED
try $EXPECTED "GET${SPACE}http://localhost${PWD}/chats.XML${SPACE}HTTP/1.0" 0 "${NONE}"

# Ppp1 ok
echo -n "Test ppp1 ok: "
echo -en "AT\nATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0\nATDT0860922000\nusername\n$PASSWORD\nWorking: Please wait...\nDone. Please logout.\n" > $EXPECTED
try $EXPECTED ppp1 0 OK 0 OK 0 CONNECT${SPACE}56000 0 login 0 password 3 logout

# Ppp1 error
echo -n "Test ppp1 ko: "
echo -en "AT\nATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0\nATDT0860922000\n" > $EXPECTED
try $EXPECTED ppp1 0 OK 0 OK 0 NO${SPACE}DIALTONE

# Ppp2
echo -n "Test ppp2: "
echo -en "OK\nOK\nCONNECT 56000\nlogin\npassword\nWorking: Please wait...\nDone. Please logout.\n" > $EXPECTED
try $EXPECTED ppp2 0 AT 0 "ATQ0${SPACE}V1${SPACE}E1${SPACE}S0=0${SPACE}&C1${SPACE}&D2${SPACE}+FCLASS=0" 0 ATDT0860922000 4 username 0 $PASSWORD 3 logout

# Multi 1
echo -n "Test Multi 1: "
echo -en "\nme\npass\nls\n" > $EXPECTED
try $EXPECTED testMulti 0 login 0 password

# Multi 2
echo -n "Test Multi 2: "
echo -en "\nme\nPASS\nls\n" > $EXPECTED
try $EXPECTED testMulti 0 login 0 PASSWORD

# Multi 3
echo -n "Test Multi 3: "
echo -en "\nme\n" > $EXPECTED
try $EXPECTED testMulti 0 login 0 Password

# Multi 4
echo -n "Test Multi 4: "
echo -en "\nME\nPASS\n" > $EXPECTED
try $EXPECTED testMulti 0 LOGIN 0 PASSWORD

# Multi 5
echo -n "Test Multi 5: "
echo -en "\n" > $EXPECTED
try $EXPECTED testMulti 0 Login

# Login OK
echo -n "Test login ok: "
echo -en "login:\npassword:\nlogin:\npassword:\nUser username logged in\nUser username logged out\n" > $EXPECTED
try $EXPECTED login 0 user 0 password 0 username 0 ${PASSWORD} 1 logout

# Login KO
echo -n "Test login ko: "
echo -en "login:\npassword:\nlogin:\npassword:\nlogin:\npassword:\nlogin:\npassword:\nlogin:\npassword:\nLogin failed\n" > $EXPECTED
try $EXPECTED login 0 user 0 password 0 user 0 password 0 user 0 password 0 user 0 password 0 user 0 password 1 logout

# Logout KO
echo -n "Test logout ko: "
echo -en "" > $EXPECTED
try $EXPECTED logout

# Indirect 1
echo -n "Test indirect 1: "
echo -en "Content2\n" > $EXPECTED
try $EXPECTED indirect 0 1

# Indirect a
echo -n "Test indirect a: "
echo -en "ERROR\n" > $EXPECTED
try $EXPECTED indirect 0 a

# Indirect 2
echo -n "Test indirect 2: "
echo -en "ERROR\n" > $EXPECTED
try $EXPECTED indirect 0 2

# Indirect timeout
echo -n "Test indirect timeout: "
echo -en "TIMEOUT\n" > $EXPECTED
try $EXPECTED indirect 2

# Error 1 (nothing after handler)
echo -n "Test error1: "
echo -en "error-handler-1\n" > $EXPECTED
try $EXPECTED error1

# Error 2 (a send after handler)
echo -n "Test error2: "
echo -en "error-handler-2\nafter-error-2\n" > $EXPECTED
try $EXPECTED error2

# Parse 1
echo -n "Test parse 1: "
echo -en "toto\n" > $EXPECTED
try $EXPECTED parse${SPACE}toto

# Parse 3
echo -n "Test parse 3: "
echo -en "toto\ntiti\ntata\n" > $EXPECTED
try $EXPECTED parse${SPACE}toto${SPACE}titi${SPACE}tata

# Parse 6
echo -n "Test parse 6: "
echo -en "toto\ntiti\ntata\ntutu\ntete\n" > $EXPECTED
try $EXPECTED parse${SPACE}toto${SPACE}titi${SPACE}tata${SPACE}tutu${SPACE}tete${SPACE}nene

# Eval compute, resolve and none
echo -n "Test eval compute: "
echo "21" > $EXPECTED
try $EXPECTED "compute 0 3*7"
echo -n "Test eval resolve: "
echo "${PWD}" > $EXPECTED
try $EXPECTED "resolve 0 \${\$PWD}"
echo -n "Test eval none: "
echo "none" > $EXPECTED
try $EXPECTED "none 0 \${Command}"

# Clean
clean
echo "OK."

