#!/bin/bash

export PASSWORD="userpass"
export HOSTNAME
export HOSTIP=`gawk -v HOSTNAME=$HOSTNAME '
  ($2 == HOSTNAME) || ($3 == HOSTNAME) || ($4 == HOSTNAME) {
    ADDR = $1
    gsub ("\\\\.", "\\\\.", ADDR)
    print ADDR
    exit
  }
' /etc/hosts `

export TCPCHAT_DEBUG=""
export PORT="http"
export DBG=""
while [ "$1" != "" ] ; do
  if [ "$1" = "-d" ] ; then
    export tcpchat_TRACE=debug
    shift
  elif [ "$1" = "-g" ] ; then
    export DBG=gvd
    shift
  elif [ "$1" = "-p" ] ; then
    export PORT="$2"
    shift
    shift
  else
    break
  fi
done
if [ "$PORT" = "-" ] ; then
  export PORT_NAME="stdio"
else
  export PORT_NAME="port $PORT"
fi

if [ \( "$1" = "-h" \) -o \( "$1" = "--help" \) ] ; then
  echo "Usage: `basename $0` [ -d ] [ -g] [ -p <port> ]  <chats_file>"
  echo " -d             for tcpchat debug traces"
  echo " -g             for launching debugger"
  echo " -p <port>      for specific port or stdin if \"-\" (default \"http\")"
  echo " http, rsh, chats or other xml file name"
  echo "Note that using the port http requires root priviledges."
  exit 1
fi
if [ -f "$1.xml" ] ; then
  FILE="$1.xml"
  echo "Chats $FILE on $PORT_NAME"
else
  echo "File "$1.xml" not found."
  exit 1
fi

exec $DBG tcpchat -p $PORT -f $FILE

