#!/bin/bash

export PASSWORD="userpass"
export HOSTNAME
export HOSTIP=`gawk -v HOSTNAME=$HOSTNAME '
  ($2 == HOSTNAME) {
    ADDR = $1
    gsub ("\\\\.", "\\\\.", ADDR)
    print ADDR
    exit
  }
' /etc/hosts `

if [ "$1" = "-d" ] ; then
  export TCPCHAT_DEBUG=Y
  shift
fi

if [ "$1" = "http" ] ; then
  port="www"
  file=http-rsh.xml
  echo "On port $port"
elif [ "$1" != "" ] ; then
  port="$1"
  file=chats.xml
  echo "On port $port"
else
  port="-"
  file=chats.xml
  echo "On stdio"
fi

exec tcpchat -p $port -f $file

