#!/bin/bash

export PASSWORD="userpass"
export HOSTNAME
export HOSTIP=`gawk -v HOSTNAME=$HOSTNAME '
  ($2 == HOSTNAME) {
    ADDR = $1
    gsub ("\\\\.", "\\\\.", ADDR)
    print ADDR
    exit
  }
' /etc/hosts `


export TCPCHAT_DEBUG=""
export PORT="http"
while [ "$1" != "" ] ; do
  if [ "$1" = "-d" ] ; then
    export TCPCHAT_DEBUG=Y
    shift
  elif [ "$1" = "-p" ] ; then
    export PORT="$2"
    shift
    shift
  else
    break
  fi
done
if [ "$PORT" = "-" ] ; then
  export PORT_ENAME="stdio"
else
  export PORT_NAME="port $PORT"
fi

if [ "$1" = "http" ] ; then
  FILE=http-rsh.xml
  echo "Http on $PORT_NAME"
elif [ "$1" = "chats" ] ; then
  FILE=chats.xml
  echo "Chats on $PORT_NAME"
else
  echo "Usage: `basename $0` [ -d ] [ -p <port> ]  http | chats"
  exit 1
fi

exec tcpchat -p $PORT -f $FILE

