with As.U;
package Ctrynams_Short is

Isofullname : constant array (Positive range <>) of As.U.Asu_Us := (
As.U.Tus ("Vatican (Holy See)"),
As.U.Tus ("Monaco"),
As.U.Tus ("Gibraltar"),
As.U.Tus ("Tokelau"),
As.U.Tus ("Cocos Islands (Keeling Islands)"),
As.U.Tus ("Saint-Barthelemy"),
As.U.Tus ("Nauru"),
As.U.Tus ("Tuvalu"),
As.U.Tus ("Macau (Aomen)"),
As.U.Tus ("Sint Maarten"),
As.U.Tus ("Saint Martin"),
As.U.Tus ("Norfolk and Philip Island (Philip Island) (Norfolk Island)"),
As.U.Tus ("Pitcairn Islands (Pitcairn, Henderson, Ducie and Oeno Islands)"),
As.U.Tus ("Bouvet Island"),
As.U.Tus ("Bermuda (Somers Isles)"),
As.U.Tus ("British Indian Ocean Territory"),
As.U.Tus ("San Marino"),
As.U.Tus ("Guernsey"),
As.U.Tus ("Anguilla"),
As.U.Tus ("Montserrat"),
As.U.Tus ("Jersey"),
As.U.Tus ("Christmas Island"),
As.U.Tus ("Wallis and Futuna (Futuna) (Wallis)"),
As.U.Tus ("British Virgin Islands (Virgin Islands, British)"),
As.U.Tus ("Liechtenstein"),
As.U.Tus ("Aruba"),
As.U.Tus ("Marshall Islands"),
As.U.Tus ("American Samoa (Samoa, American)"),
As.U.Tus ("Cook Islands"),
As.U.Tus ("Saint Pierre and Miquelon (Miquelon) (Saint Pierre)"),
As.U.Tus ("Niue"),
As.U.Tus ("Saint Kitts and Nevis (Nevis) (Saint Kitts)"),
As.U.Tus ("Cayman islands"),
As.U.Tus ("Bonaire, St Eustasuis and Saba (Bonaire) (Saba) (St Eustasius)"),
As.U.Tus ("Maldives"),
As.U.Tus ("Saint Helena, Ascension and Tristan da Cunha (Saint Helena) (Ascension) (Tristan da Cunha)"),
As.U.Tus ("Malta"),
As.U.Tus ("Grenada"),
As.U.Tus ("Virgin Islands of the United States (US Virgin Islands) (American Virgin Islands)"),
As.U.Tus ("Mayotte (Maore)"),
As.U.Tus ("Svalbard and Jan Mayen (Svalbard) (Jan Mayen) (Spitsbergen)"),
As.U.Tus ("Saint Vincent and the Grenadines (Saint Vincent) (Grenadines)"),
As.U.Tus ("Heard Island and McDonald Islands (Heard Island) (McDonald Islands)"),
As.U.Tus ("Barbados"),
As.U.Tus ("Antigua and Barbuda (Antigua) (Barbuda)"),
As.U.Tus ("Curacao"),
As.U.Tus ("Seychelles"),
As.U.Tus ("Palau"),
As.U.Tus ("Northern Mariana Islands"),
As.U.Tus ("Andorra"),
As.U.Tus ("Guam"),
As.U.Tus ("Isle of Mann (Mann)"),
As.U.Tus ("Saint Lucia"),
As.U.Tus ("Micronesia (Federated States of Micronesia)"),
As.U.Tus ("Singapore"),
As.U.Tus ("Tonga"),
As.U.Tus ("Dominica"),
As.U.Tus ("Bahrain"),
As.U.Tus ("Kiribati"),
As.U.Tus ("Turks and Caicos Islands (Turks Islands) (Caicos Islands)"),
As.U.Tus ("Sao Tome and Principe (Sao Tome) (Principe)"),
As.U.Tus ("Hong Kong (Xianggang)"),
As.U.Tus ("Martinique"),
As.U.Tus ("Faroe Islands"),
As.U.Tus ("Guadeloupe"),
As.U.Tus ("Comoros"),
As.U.Tus ("Mauritius"),
As.U.Tus ("Reunion"),
As.U.Tus ("Luxembourg"),
As.U.Tus ("Samoa"),
As.U.Tus ("South Georgia and the South Sandwich Islands (South Georgia) (South Sandwich Islands)"),
As.U.Tus ("French Polynesia"),
As.U.Tus ("Cape Verde (Cabo Verde) (Republic of Cabo Verde)"),
As.U.Tus ("Trinidad and Tobago (Trinidad) (Tobago)"),
As.U.Tus ("Brunei"),
As.U.Tus ("French Southern and Antarctic Lands"),
As.U.Tus ("Puerto Rico"),
As.U.Tus ("Cyprus"),
As.U.Tus ("Lebanon (Lebanese Republic)"),
As.U.Tus ("Jamaica"),
As.U.Tus ("Gambia (The Gambia)"),
As.U.Tus ("Qatar"),
As.U.Tus ("Falkland Islands (The Falklands)"),
As.U.Tus ("Vanuatu"),
As.U.Tus ("Montenegro"),
As.U.Tus ("Bahamas"),
As.U.Tus ("Timor-Leste (East Timor)"),
As.U.Tus ("Swaziland"),
As.U.Tus ("Kuwait"),
As.U.Tus ("Fiji"),
As.U.Tus ("New Caledonia"),
As.U.Tus ("Slovenia"),
As.U.Tus ("Israel"),
As.U.Tus ("Palestinian territories (State of Palestine)"),
As.U.Tus ("El Salvador"),
As.U.Tus ("Belize"),
As.U.Tus ("Djibouti"),
As.U.Tus ("Macedonia (FYROM) (Former Yugoslav Republic of Macedonia)"),
As.U.Tus ("Rwanda"),
As.U.Tus ("Haiti"),
As.U.Tus ("Burundi"),
As.U.Tus ("Equatorial Guinea"),
As.U.Tus ("Albania"),
As.U.Tus ("Solomon Islands"),
As.U.Tus ("Armenia"),
As.U.Tus ("Lesotho"),
As.U.Tus ("Belgium"),
As.U.Tus ("Moldova"),
As.U.Tus ("Guinea-Bissau"),
As.U.Tus ("Taiwan (Republic of China)"),
As.U.Tus ("Bhutan"),
As.U.Tus ("Switzerland (Swiss Confederation)"),
As.U.Tus ("Netherlands (The Netherlands)"),
As.U.Tus ("Denmark"),
As.U.Tus ("Estonia"),
As.U.Tus ("Dominican Republic"),
As.U.Tus ("Slovakia (Slovak Republic)"),
As.U.Tus ("Costa Rica"),
As.U.Tus ("Bosnia and Herzegovina"),
As.U.Tus ("Croatia"),
As.U.Tus ("Togo (Togolese Republic)"),
As.U.Tus ("Latvia"),
As.U.Tus ("Lithuania"),
As.U.Tus ("Sri Lanka"),
As.U.Tus ("Georgia"),
As.U.Tus ("Ireland"),
As.U.Tus ("Sierra Leone"),
As.U.Tus ("Panama"),
As.U.Tus ("Czech Republic"),
As.U.Tus ("French Guiana (Guiana)"),
As.U.Tus ("United Arab Emirates (Emirates)"),
As.U.Tus ("Austria"),
As.U.Tus ("Azerbaijan"),
As.U.Tus ("Serbia"),
As.U.Tus ("Jordan"),
As.U.Tus ("Portugal (Portuguese Republic)"),
As.U.Tus ("Hungary"),
As.U.Tus ("South Korea (Republic of Korea) (Korea, South)"),
As.U.Tus ("Iceland"),
As.U.Tus ("Guatemala"),
As.U.Tus ("Cuba"),
As.U.Tus ("Bulgaria"),
As.U.Tus ("Liberia"),
As.U.Tus ("Honduras"),
As.U.Tus ("Benin"),
As.U.Tus ("Eritrea"),
As.U.Tus ("Malawi"),
As.U.Tus ("North Korea (Democratic People's Republic of Korea) (Korea, North)"),
As.U.Tus ("Nicaragua"),
As.U.Tus ("Greece (Hellenic Republic) (Hellas)"),
As.U.Tus ("Tajikistan"),
As.U.Tus ("Bangladesh"),
As.U.Tus ("Nepal"),
As.U.Tus ("Tunisia (Tunisian Republic)"),
As.U.Tus ("Suriname"),
As.U.Tus ("Uruguay"),
As.U.Tus ("Cambodia"),
As.U.Tus ("Syria (Syrian Arab Republic)"),
As.U.Tus ("Senegal"),
As.U.Tus ("Kyrgyzstan (Kyrgyz Republic)"),
As.U.Tus ("Belarus"),
As.U.Tus ("Guyana"),
As.U.Tus ("Laos (Lao People's Democratic Republic)"),
As.U.Tus ("Romania"),
As.U.Tus ("Ghana"),
As.U.Tus ("Uganda"),
As.U.Tus ("United Kingdom (Scotland) (Great Britain) (England) "
        & "(Northern Ireland) (Ireland, Northern) (Britain) "
        & "(United Kingdom of Great Britain and Northern Ireland)"),
As.U.Tus ("Guinea (Guinea-Conakry)"),
As.U.Tus ("Ecuador"),
As.U.Tus ("Western Sahara (Sahrawi Arab Democratic Republic)"),
As.U.Tus ("Gabon (Gabonese Republic)"),
As.U.Tus ("New Zealand"),
As.U.Tus ("Burkina Faso"),
As.U.Tus ("Philippines"),
As.U.Tus ("Italy (Italian Republic)"),
As.U.Tus ("Oman"),
As.U.Tus ("Poland"),
As.U.Tus ("Ivory Coast (Cote d'Ivoire) (Republic of Cote d'Ivoire)"),
As.U.Tus ("Norway"),
As.U.Tus ("Malaysia"),
As.U.Tus ("Vietnam"),
As.U.Tus ("Finland"),
As.U.Tus ("Congo-Brazzaville (West Congo) (Republic of the Congo)"),
As.U.Tus ("Germany"),
As.U.Tus ("Japan"),
As.U.Tus ("Zimbabwe"),
As.U.Tus ("Paraguay"),
As.U.Tus ("Iraq"),
As.U.Tus ("Morocco"),
As.U.Tus ("Uzbekistan"),
As.U.Tus ("Sweden"),
As.U.Tus ("Papua New Guinea"),
As.U.Tus ("Cameroon"),
As.U.Tus ("Turkmenistan"),
As.U.Tus ("Spain"),
As.U.Tus ("Thailand"),
As.U.Tus ("Yemen"),
As.U.Tus ("France (French Republic)"),
As.U.Tus ("Aaland Islands"),
As.U.Tus ("Kenya"),
As.U.Tus ("Botswana"),
As.U.Tus ("Madagascar"),
As.U.Tus ("Ukraine"),
As.U.Tus ("South Sudan"),
As.U.Tus ("Central African Republic"),
As.U.Tus ("Somalia"),
As.U.Tus ("Afghanistan"),
As.U.Tus ("Myanmar (Burma)"),
As.U.Tus ("Zambia"),
As.U.Tus ("Chile"),
As.U.Tus ("Turkey"),
As.U.Tus ("Pakistan"),
As.U.Tus ("Mozambique"),
As.U.Tus ("Namibia"),
As.U.Tus ("Venezuela"),
As.U.Tus ("Nigeria"),
As.U.Tus ("Tanzania"),
As.U.Tus ("Egypt"),
As.U.Tus ("Mauritania"),
As.U.Tus ("Bolivia"),
As.U.Tus ("Ethiopia"),
As.U.Tus ("Colombia"),
As.U.Tus ("South Africa"),
As.U.Tus ("Mali"),
As.U.Tus ("Angola"),
As.U.Tus ("Niger"),
As.U.Tus ("Chad"),
As.U.Tus ("Peru"),
As.U.Tus ("Mongolia"),
As.U.Tus ("Iran (Persia)"),
As.U.Tus ("Libya"),
As.U.Tus ("Sudan"),
As.U.Tus ("Indonesia"),
As.U.Tus ("Federal District"),
As.U.Tus ("Tlaxcala"),
As.U.Tus ("Morelos"),
As.U.Tus ("Aguascalientes"),
As.U.Tus ("Colima"),
As.U.Tus ("Queretaro"),
As.U.Tus ("Hidalgo"),
As.U.Tus ("Mexico State"),
As.U.Tus ("Tabasco"),
As.U.Tus ("Nayarit"),
As.U.Tus ("Guanajuato"),
As.U.Tus ("Puebla"),
As.U.Tus ("Yucatan"),
As.U.Tus ("Quintana Roo"),
As.U.Tus ("Sinaloa"),
As.U.Tus ("Campeche"),
As.U.Tus ("Michoacan"),
As.U.Tus ("San Luis Potosi"),
As.U.Tus ("Guerrero"),
As.U.Tus ("Nuevo Leon (New Leon)"),
As.U.Tus ("Baja California"),
As.U.Tus ("Veracruz"),
As.U.Tus ("Chiapas"),
As.U.Tus ("Baja California Sur"),
As.U.Tus ("Zacatecas"),
As.U.Tus ("Jalisco"),
As.U.Tus ("Tamaulipas"),
As.U.Tus ("Oaxaca"),
As.U.Tus ("Durango"),
As.U.Tus ("Coahuila"),
As.U.Tus ("Sonora"),
As.U.Tus ("Chihuahua"),
As.U.Tus ("Greenland"),
As.U.Tus ("Saudi Arabia"),
As.U.Tus ("Congo-Kinshasa (Democratic Republic of the Congo) (East Congo)"),
As.U.Tus ("Algeria"),
As.U.Tus ("Kazakhstan"),
As.U.Tus ("Argentina (Argentine Republic)"),
As.U.Tus ("Daman and Diu"),
As.U.Tus ("Dadra and Nagar Haveli (Dadra) (Nagar Haveli)"),
As.U.Tus ("Chandigarh"),
As.U.Tus ("Andaman and Nicobar (Andaman) (Nicobar)"),
As.U.Tus ("Lakshadweep"),
As.U.Tus ("Delhi"),
As.U.Tus ("Meghalaya"),
As.U.Tus ("Nagaland"),
As.U.Tus ("Manipur"),
As.U.Tus ("Tripura"),
As.U.Tus ("Mizoram"),
As.U.Tus ("Sikkim"),
As.U.Tus ("Punjab"),
As.U.Tus ("Haryana"),
As.U.Tus ("Arunachal Pradesh"),
As.U.Tus ("Assam"),
As.U.Tus ("Bihar"),
As.U.Tus ("Uttarakhand"),
As.U.Tus ("Goa"),
As.U.Tus ("Kerala"),
As.U.Tus ("Tamil Nadu"),
As.U.Tus ("Himachal Pradesh"),
As.U.Tus ("Jammu and Kashmir (Jammu) (Kashmir)"),
As.U.Tus ("Chhattisgarh"),
As.U.Tus ("Jharkhand"),
As.U.Tus ("Karnataka"),
As.U.Tus ("Rajasthan"),
As.U.Tus ("Odisha (Orissa)"),
As.U.Tus ("Gujarat"),
As.U.Tus ("West Bengal"),
As.U.Tus ("Madhya Pradesh"),
As.U.Tus ("Telangana"),
As.U.Tus ("Andhra Pradesh"),
As.U.Tus ("Maharashtra"),
As.U.Tus ("Uttar Pradesh"),
As.U.Tus ("Puducherry"),
As.U.Tus ("New South Wales"),
As.U.Tus ("Australian Capital Territory"),
As.U.Tus ("Jervis Bay Territory"),
As.U.Tus ("Northern Territory"),
As.U.Tus ("South Australia"),
As.U.Tus ("Tasmania"),
As.U.Tus ("Victoria"),
As.U.Tus ("Western Australia"),
As.U.Tus ("Queensland"),
As.U.Tus ("Distrito Federal"),
As.U.Tus ("Sergipe"),
As.U.Tus ("Alagoas"),
As.U.Tus ("Rio de Janeiro"),
As.U.Tus ("Espirito Santo"),
As.U.Tus ("Rio Grande do Norte"),
As.U.Tus ("Paraiba"),
As.U.Tus ("Santa Catarina"),
As.U.Tus ("Pernambuco"),
As.U.Tus ("Amapa"),
As.U.Tus ("Ceara"),
As.U.Tus ("Acre"),
As.U.Tus ("Parana"),
As.U.Tus ("Roraima"),
As.U.Tus ("Rondonia"),
As.U.Tus ("Sao Paulo"),
As.U.Tus ("Piaui"),
As.U.Tus ("Tocantins"),
As.U.Tus ("Rio Grande do Sul"),
As.U.Tus ("Maranhao"),
As.U.Tus ("Goias"),
As.U.Tus ("Mato Grosso do Sul"),
As.U.Tus ("Bahia"),
As.U.Tus ("Minas Gerais"),
As.U.Tus ("Mato Grosso"),
As.U.Tus ("Para"),
As.U.Tus ("Amazonas"),
As.U.Tus ("District of Columbia (Washington, D.C.)"),
As.U.Tus ("Rhode Island"),
As.U.Tus ("Delaware"),
As.U.Tus ("Connecticut"),
As.U.Tus ("New Jersey"),
As.U.Tus ("New Hampshire"),
As.U.Tus ("Vermont"),
As.U.Tus ("Massachusetts"),
As.U.Tus ("Hawaii"),
As.U.Tus ("Maryland"),
As.U.Tus ("West Virginia"),
As.U.Tus ("South Carolina"),
As.U.Tus ("Maine"),
As.U.Tus ("Indiana"),
As.U.Tus ("Kentucky"),
As.U.Tus ("Tennessee"),
As.U.Tus ("Virginia"),
As.U.Tus ("Ohio"),
As.U.Tus ("Pennsylvania"),
As.U.Tus ("Mississippi"),
As.U.Tus ("Louisiana"),
As.U.Tus ("Alabama"),
As.U.Tus ("Arkansas"),
As.U.Tus ("North Carolina"),
As.U.Tus ("New York"),
As.U.Tus ("Iowa"),
As.U.Tus ("Illinois"),
As.U.Tus ("Georgia"),
As.U.Tus ("Wisconsin"),
As.U.Tus ("Florida"),
As.U.Tus ("Missouri"),
As.U.Tus ("Oklahoma"),
As.U.Tus ("North Dakota"),
As.U.Tus ("Washington"),
As.U.Tus ("South Dakota"),
As.U.Tus ("Nebraska"),
As.U.Tus ("Kansas"),
As.U.Tus ("Idaho"),
As.U.Tus ("Utah"),
As.U.Tus ("Minnesota"),
As.U.Tus ("Michigan"),
As.U.Tus ("Wyoming"),
As.U.Tus ("Oregon"),
As.U.Tus ("Colorado"),
As.U.Tus ("Nevada"),
As.U.Tus ("Arizona"),
As.U.Tus ("New Mexico"),
As.U.Tus ("Montana"),
As.U.Tus ("California"),
As.U.Tus ("Texas"),
As.U.Tus ("Alaska"),
As.U.Tus ("British Columbia"),
As.U.Tus ("Alberta"),
As.U.Tus ("Ontario"),
As.U.Tus ("Quebec"),
As.U.Tus ("Saskatchewan"),
As.U.Tus ("Manitoba"),
As.U.Tus ("Newfoundland and Labrador (Newfoundland) (Labrador)"),
As.U.Tus ("New Brunswick"),
As.U.Tus ("Nova Scotia"),
As.U.Tus ("Prince Edward Island"),
As.U.Tus ("Yukon"),
As.U.Tus ("Northwest Territories"),
As.U.Tus ("Nunavut"),
As.U.Tus ("India"),
As.U.Tus ("Australia"),
As.U.Tus ("Brazil"),
As.U.Tus ("USA (United States of America) (America)"),
As.U.Tus ("Mexico (United Mexican States)"),
As.U.Tus ("Moscow"),
As.U.Tus ("Saint Petersburg"),
As.U.Tus ("Kaliningrad Oblast"),
As.U.Tus ("Ingushetia"),
As.U.Tus ("Adygea Republic"),
As.U.Tus ("North Ossetia-Alania Republic"),
As.U.Tus ("Kabardino-Balkar Republic"),
As.U.Tus ("Karachay-Cherkess Republic"),
As.U.Tus ("Chechen Republic (Chechnya) (Ichkeria)"),
As.U.Tus ("Chuvash Republic"),
As.U.Tus ("Ivanovo Oblast"),
As.U.Tus ("Lipetsk Oblast"),
As.U.Tus ("Oryol Oblast"),
As.U.Tus ("Tula Oblast"),
As.U.Tus ("Belgorod Oblast"),
As.U.Tus ("Vladimir Oblast"),
As.U.Tus ("Kursk Oblast"),
As.U.Tus ("Kaluga Oblast"),
As.U.Tus ("Tambov Oblast"),
As.U.Tus ("Bryansk Oblast"),
As.U.Tus ("Yaroslavl Oblast"),
As.U.Tus ("Ryazan Oblast"),
As.U.Tus ("Astrakhan Oblast"),
As.U.Tus ("Moscow Oblast"),
As.U.Tus ("Smolensk Oblast"),
As.U.Tus ("Dagestan Republic"),
As.U.Tus ("Voronezh Oblast"),
As.U.Tus ("Novgorod Oblast"),
As.U.Tus ("Pskov Oblast"),
As.U.Tus ("Kostroma Oblast"),
As.U.Tus ("Stavropol Krai"),
As.U.Tus ("Krasnodar Krai"),
As.U.Tus ("Kalmykia Republic"),
As.U.Tus ("Tver Oblast"),
As.U.Tus ("Leningrad Oblast"),
As.U.Tus ("Rostov Oblast"),
As.U.Tus ("Volgograd Oblast"),
As.U.Tus ("Vologda Oblast"),
As.U.Tus ("Murmansk Oblast"),
As.U.Tus ("Karelia Republic"),
As.U.Tus ("Nenets Autonomous Okrug"),
As.U.Tus ("Komi Republic"),
As.U.Tus ("Arkhangelsk Oblast"),
As.U.Tus ("Mordovia Republic"),
As.U.Tus ("Nizhny Novgorod Oblast"),
As.U.Tus ("Penza Oblast"),
As.U.Tus ("Kirov Oblast"),
As.U.Tus ("Mari El Republic"),
As.U.Tus ("Orenburg Oblast"),
As.U.Tus ("Ulyanovsk Oblast"),
As.U.Tus ("Perm Krai"),
As.U.Tus ("Bashkortostan Republic"),
As.U.Tus ("Udmurt Republic"),
As.U.Tus ("Tatarstan Republic"),
As.U.Tus ("Samara Oblast"),
As.U.Tus ("Saratov Oblast"),
As.U.Tus ("Yamalo-Nenets"),
As.U.Tus ("Khanty-Mansi"),
As.U.Tus ("Sverdlovsk Oblast"),
As.U.Tus ("Tyumen Oblast"),
As.U.Tus ("Kurgan Oblast"),
As.U.Tus ("Chelyabinsk Oblast"),
As.U.Tus ("Buryatia Republic"),
As.U.Tus ("Zabaykalsky Krai"),
As.U.Tus ("Irkutsk Oblast"),
As.U.Tus ("Novosibirsk Oblast"),
As.U.Tus ("Tomsk Oblast"),
As.U.Tus ("Omsk Oblast"),
As.U.Tus ("Khakassia Republic"),
As.U.Tus ("Kemerovo Oblast"),
As.U.Tus ("Altai Republic"),
As.U.Tus ("Altai Krai"),
As.U.Tus ("Tuva Republic"),
As.U.Tus ("Krasnoyarsk Krai"),
As.U.Tus ("Magadan Oblast"),
As.U.Tus ("Chukotka Okrug"),
As.U.Tus ("Kamchatka Krai"),
As.U.Tus ("Sakhalin Oblast"),
As.U.Tus ("Primorsky Krai"),
As.U.Tus ("Jewish Autonomous Oblast"),
As.U.Tus ("Khabarovsk Krai"),
As.U.Tus ("Amur Oblast"),
As.U.Tus ("Sakha Republic (Yakutia Republic)"),
As.U.Tus ("Canada"),
As.U.Tus ("Russia (Russian Federation)"),
As.U.Tus ("Shanghai"),
As.U.Tus ("Tianjin"),
As.U.Tus ("Beijing"),
As.U.Tus ("Hainan"),
As.U.Tus ("Ningxia Hui"),
As.U.Tus ("Chongqing"),
As.U.Tus ("Zhejiang"),
As.U.Tus ("Jiangsu"),
As.U.Tus ("Fujian"),
As.U.Tus ("Anhui"),
As.U.Tus ("Liaoning"),
As.U.Tus ("Shandong"),
As.U.Tus ("Shanxi"),
As.U.Tus ("Jiangxi"),
As.U.Tus ("Henan"),
As.U.Tus ("Guizhou"),
As.U.Tus ("Guangdong"),
As.U.Tus ("Hubei"),
As.U.Tus ("Jilin"),
As.U.Tus ("Hebei (Yanzhao)"),
As.U.Tus ("Shaanxi"),
As.U.Tus ("Nei Mongol (Inner Mongolia)"),
As.U.Tus ("Heilongjiang"),
As.U.Tus ("Hunan"),
As.U.Tus ("Guangxi Zhuang"),
As.U.Tus ("Sichuan"),
As.U.Tus ("Yunnan"),
As.U.Tus ("Xizang (Tibet)"),
As.U.Tus ("Gansu"),
As.U.Tus ("Qinghai (Tsinghai)"),
As.U.Tus ("Xinjiang Uyghur"),
As.U.Tus ("China"),
As.U.Tus ("United States Minor Outlying Islands"),
As.U.Tus ("Clipperton Island"),
As.U.Tus ("Antarctica"),
As.U.Tus ("International (Worldwide) (Earth)"),
As.U.Tus ("?"));
end Ctrynams_Short;

