with Mapcode_Utils.As_U;
use Mapcode_Utils;
package Ctrynams is

Isofullname : constant array (Positive range <>) of As_U.Asu_Us := (
As_U.Tus ("Vatican (Holy See) (_ City State)"),
As_U.Tus ("Monaco (Principality of _)"),
As_U.Tus ("Gibraltar"),
As_U.Tus ("Tokelau"),
As_U.Tus ("Cocos Islands (Keeling Islands)"),
As_U.Tus ("Saint-Barthelemy (Collectivity of _)"),
As_U.Tus ("Nauru (Republic of _)"),
As_U.Tus ("Tuvalu"),
As_U.Tus ("Macau (Aomen)"),
As_U.Tus ("Sint Maarten"),
As_U.Tus ("Saint Martin (Collectivity of _)"),
As_U.Tus ("Norfolk and Philip Island (Philip Island) (Norfolk Island)"),
As_U.Tus ("Pitcairn Islands (Pitcairn, Henderson, Ducie and Oeno Islands)"),
As_U.Tus ("Bouvet Island"),
As_U.Tus ("Bermuda (Somers Isles)"),
As_U.Tus ("British Indian Ocean Territory"),
As_U.Tus ("San Marino (Republic of _)"),
As_U.Tus ("Guernsey (Bailiwick of _)"),
As_U.Tus ("Anguilla"),
As_U.Tus ("Montserrat"),
As_U.Tus ("Jersey (Bailiwick of _)"),
As_U.Tus ("Christmas Island"),
As_U.Tus ("Wallis and Futuna (Futuna) (Wallis) (Collectivity of the _ Islands)"),
As_U.Tus ("British Virgin Islands (Virgin Islands, British)"),
As_U.Tus ("Liechtenstein (Principality of _)"),
As_U.Tus ("Aruba"),
As_U.Tus ("Marshall Islands (Republic of the _)"),
As_U.Tus ("American Samoa (Samoa, American)"),
As_U.Tus ("Cook Islands"),
As_U.Tus ("Saint Pierre and Miquelon (Miquelon) (Saint Pierre) (Collectivity of _)"),
As_U.Tus ("Niue"),
As_U.Tus ("Saint Kitts and Nevis (Nevis) (Saint Kitts) (Federation of _)"),
As_U.Tus ("Cayman islands"),
As_U.Tus ("Bonaire, St Eustasuis and Saba (Bonaire) (Saba) (St Eustasius)"),
As_U.Tus ("Maldives (Republic of _)"),
As_U.Tus ("Saint Helena, Ascension and Tristan da Cunha (Saint Helena) (Ascension) (Tristan da Cunha)"),
As_U.Tus ("Malta (Republic of _)"),
As_U.Tus ("Grenada"),
As_U.Tus ("Virgin Islands of the United States (US Virgin Islands) (American Virgin Islands)"),
As_U.Tus ("Mayotte (Maore)"),
As_U.Tus ("Svalbard and Jan Mayen (Svalbard) (Jan Mayen) (Spitsbergen)"),
As_U.Tus ("Saint Vincent and the Grenadines (Saint Vincent) (Grenadines)"),
As_U.Tus ("Heard Island and McDonald Islands (Heard Island) (McDonald Islands)"),
As_U.Tus ("Barbados"),
As_U.Tus ("Antigua and Barbuda (Antigua) (Barbuda)"),
As_U.Tus ("Curacao"),
As_U.Tus ("Seychelles (Republic of _)"),
As_U.Tus ("Palau (Republic of _)"),
As_U.Tus ("Northern Mariana Islands (Commonwealth of the _)"),
As_U.Tus ("Andorra (Principality of _) (Principality of the Valleys of _)"),
As_U.Tus ("Guam"),
As_U.Tus ("Isle of Mann (Mann)"),
As_U.Tus ("Saint Lucia"),
As_U.Tus ("Micronesia (Federated States of Micronesia)"),
As_U.Tus ("Singapore (Republic of _)"),
As_U.Tus ("Tonga (Kingdom of _)"),
As_U.Tus ("Dominica (Commonwealth of _)"),
As_U.Tus ("Bahrain (Kingdom of _)"),
As_U.Tus ("Kiribati (Republic of _)"),
As_U.Tus ("Turks and Caicos Islands (Turks Islands) (Caicos Islands)"),
As_U.Tus ("Sao Tome and Principe (Sao Tome) (Principe) (Democratic Republic of _)"),
As_U.Tus ("Hong Kong (Xianggang)"),
As_U.Tus ("Martinique"),
As_U.Tus ("Faroe Islands"),
As_U.Tus ("Guadeloupe"),
As_U.Tus ("Comoros (Union of the _)"),
As_U.Tus ("Mauritius (Republic of _)"),
As_U.Tus ("Reunion"),
As_U.Tus ("Luxembourg (Grand Duchy of _)"),
As_U.Tus ("Samoa (Independent State of _)"),
As_U.Tus ("South Georgia and the South Sandwich Islands (South Georgia) (South Sandwich Islands)"),
As_U.Tus ("French Polynesia (Collectivity of _)"),
As_U.Tus ("Cape Verde (Cabo Verde) (Republic of Cabo Verde)"),
As_U.Tus ("Trinidad and Tobago (Republic of _) (Trinidad) (Tobago)"),
As_U.Tus ("Brunei (Nation of _, the Abode of Peace)"),
As_U.Tus ("French Southern and Antarctic Lands"),
As_U.Tus ("Puerto Rico (Commonwealth of _)"),
As_U.Tus ("Cyprus (Republic of _)"),
As_U.Tus ("Lebanon (Lebanese Republic)"),
As_U.Tus ("Jamaica"),
As_U.Tus ("Gambia (The Gambia) (Republic of the _)"),
As_U.Tus ("Qatar (State of _)"),
As_U.Tus ("Falkland Islands (The Falklands)"),
As_U.Tus ("Vanuatu (Republic of _)"),
As_U.Tus ("Montenegro"),
As_U.Tus ("Bahamas (Commonwealth of the _)"),
As_U.Tus ("Timor-Leste (Democratic Republic of _) (East Timor)"),
As_U.Tus ("Swaziland (Kingdom of _)"),
As_U.Tus ("Kuwait (State of _)"),
As_U.Tus ("Fiji (Republic of _)"),
As_U.Tus ("New Caledonia"),
As_U.Tus ("Slovenia (Republic of _)"),
As_U.Tus ("Israel (State of _)"),
As_U.Tus ("Palestinian territories (State of Palestine)"),
As_U.Tus ("El Salvador (Republic of _)"),
As_U.Tus ("Belize"),
As_U.Tus ("Djibouti (Republic of _)"),
As_U.Tus ("Macedonia (Republic of _) (FYROM) (Former Yugoslav Republic of Macedonia)"),
As_U.Tus ("Rwanda (Republic of _)"),
As_U.Tus ("Haiti (Republic of _)"),
As_U.Tus ("Burundi (Republic of _)"),
As_U.Tus ("Equatorial Guinea (Republic of _)"),
As_U.Tus ("Albania (Republic of _)"),
As_U.Tus ("Solomon Islands"),
As_U.Tus ("Armenia (Republic of _)"),
As_U.Tus ("Lesotho (Kingdom of _)"),
As_U.Tus ("Belgium (Kingdom of _)"),
As_U.Tus ("Moldova (Republic of _)"),
As_U.Tus ("Guinea-Bissau (Republic of _)"),
As_U.Tus ("Taiwan (Republic of China)"),
As_U.Tus ("Bhutan (Kingdom of _)"),
As_U.Tus ("Switzerland (Swiss Confederation)"),
As_U.Tus ("Netherlands (The Netherlands) (Kingdom of the _)"),
As_U.Tus ("Denmark (Kingdom of _)"),
As_U.Tus ("Estonia (Republic of _)"),
As_U.Tus ("Dominican Republic"),
As_U.Tus ("Slovakia (Slovak Republic)"),
As_U.Tus ("Costa Rica (Republic of _)"),
As_U.Tus ("Bosnia and Herzegovina"),
As_U.Tus ("Croatia (Republic of _)"),
As_U.Tus ("Togo (Togolese Republic)"),
As_U.Tus ("Latvia (Republic of _)"),
As_U.Tus ("Lithuania (Republic of _)"),
As_U.Tus ("Sri Lanka (Democratic Socialist Republic of _)"),
As_U.Tus ("Georgia"),
As_U.Tus ("Ireland (Republic of _)"),
As_U.Tus ("Sierra Leone (Republic of _)"),
As_U.Tus ("Panama (Republic of _)"),
As_U.Tus ("Czech Republic"),
As_U.Tus ("French Guiana (Guiana)"),
As_U.Tus ("United Arab Emirates (Emirates)"),
As_U.Tus ("Austria (Republic of _)"),
As_U.Tus ("Azerbaijan (Republic of _)"),
As_U.Tus ("Serbia (Republic of _)"),
As_U.Tus ("Jordan (Hashemite Kingdom of _) (Kingdom of _)"),
As_U.Tus ("Portugal (Portuguese Republic)"),
As_U.Tus ("Hungary (Republic of _)"),
As_U.Tus ("South Korea (Republic of Korea) (Korea, South)"),
As_U.Tus ("Iceland"),
As_U.Tus ("Guatemala (Republic of _)"),
As_U.Tus ("Cuba (Republic of _)"),
As_U.Tus ("Bulgaria (Republic of _)"),
As_U.Tus ("Liberia (Republic of _)"),
As_U.Tus ("Honduras (Republic of _)"),
As_U.Tus ("Benin (Republic of _)"),
As_U.Tus ("Eritrea (State of _)"),
As_U.Tus ("Malawi (Republic of _)"),
As_U.Tus ("North Korea (Democratic People's Republic of Korea) (Korea, North)"),
As_U.Tus ("Nicaragua (Republic of _)"),
As_U.Tus ("Greece (Hellenic Republic) (Hellas)"),
As_U.Tus ("Tajikistan (Republic of _)"),
As_U.Tus ("Bangladesh (People's Republic of _)"),
As_U.Tus ("Nepal (Federal Democratic Republic of _)"),
As_U.Tus ("Tunisia (Tunisian Republic) (Republic of _)"),
As_U.Tus ("Suriname (Republic of _)"),
As_U.Tus ("Uruguay (Eastern Republic of _)"),
As_U.Tus ("Cambodia (Kingdom of _)"),
As_U.Tus ("Syria (Syrian Arab Republic)"),
As_U.Tus ("Senegal (Republic of _)"),
As_U.Tus ("Kyrgyzstan (Kyrgyz Republic)"),
As_U.Tus ("Belarus (Republic of _)"),
As_U.Tus ("Guyana (Co-operative Republic of _)"),
As_U.Tus ("Laos (Lao People's Democratic Republic)"),
As_U.Tus ("Romania"),
As_U.Tus ("Ghana (Republic of _)"),
As_U.Tus ("Uganda (Republic of _)"),
As_U.Tus ("United Kingdom (Scotland) (Great Britain) (England) "
        & "(Northern Ireland) (Ireland, Northern) (Britain) "
        & "(United Kingdom of Great Britain and Northern Ireland)"),
As_U.Tus ("Guinea (Republic of _) (Guinea-Conakry)"),
As_U.Tus ("Ecuador (Republic of _)"),
As_U.Tus ("Western Sahara (Sahrawi Arab Democratic Republic)"),
As_U.Tus ("Gabon (Gabonese Republic)"),
As_U.Tus ("New Zealand"),
As_U.Tus ("Burkina Faso"),
As_U.Tus ("Philippines (Republic of the _)"),
As_U.Tus ("Italy (Italian Republic)"),
As_U.Tus ("Oman (Sultanate of _)"),
As_U.Tus ("Poland (Republic of _)"),
As_U.Tus ("Ivory Coast (Cote d'Ivoire) (Republic of Cote d'Ivoire)"),
As_U.Tus ("Norway (Kingdom of _)"),
As_U.Tus ("Malaysia"),
As_U.Tus ("Vietnam (Socialist Republic of _)"),
As_U.Tus ("Finland (Republic of _)"),
As_U.Tus ("Congo-Brazzaville (West Congo) (Republic of the Congo)"),
As_U.Tus ("Germany (Federal Republic of _)"),
As_U.Tus ("Japan"),
As_U.Tus ("Zimbabwe (Republic of _)"),
As_U.Tus ("Paraguay (Republic of _)"),
As_U.Tus ("Iraq (Republic of _)"),
As_U.Tus ("Morocco (Kingdom of _)"),
As_U.Tus ("Uzbekistan (Republic of _)"),
As_U.Tus ("Sweden (Kingdom of _)"),
As_U.Tus ("Papua New Guinea (Independent State of _)"),
As_U.Tus ("Cameroon (Republic of _)"),
As_U.Tus ("Turkmenistan"),
As_U.Tus ("Spain (Kingdom of _)"),
As_U.Tus ("Thailand (Kingdom of _)"),
As_U.Tus ("Yemen (Republic of _)"),
As_U.Tus ("France (French Republic)"),
As_U.Tus ("Aaland Islands"),
As_U.Tus ("Kenya (Republic of _)"),
As_U.Tus ("Botswana (Republic of _)"),
As_U.Tus ("Madagascar (Republic of _)"),
As_U.Tus ("Ukraine"),
As_U.Tus ("South Sudan (Republic of _)"),
As_U.Tus ("Central African Republic"),
As_U.Tus ("Somalia (Federal Republic of _)"),
As_U.Tus ("Afghanistan (Islamic Republic of _)"),
As_U.Tus ("Myanmar (Republic of the Union of _) (Burma)"),
As_U.Tus ("Zambia (Republic of _)"),
As_U.Tus ("Chile (Republic of _)"),
As_U.Tus ("Turkey (Republic of _)"),
As_U.Tus ("Pakistan (Islamic Republic of _)"),
As_U.Tus ("Mozambique (Republic of _)"),
As_U.Tus ("Namibia (Republic of _)"),
As_U.Tus ("Venezuela (Bolivarian Republic of _)"),
As_U.Tus ("Nigeria (Federal Republic of _)"),
As_U.Tus ("Tanzania (United Republic of _)"),
As_U.Tus ("Egypt (Arab Republic of _)"),
As_U.Tus ("Mauritania (Islamic Republic of _)"),
As_U.Tus ("Bolivia (Plurinational State of _)"),
As_U.Tus ("Ethiopia (Federal Democratic Republic of _)"),
As_U.Tus ("Colombia (Republic of _)"),
As_U.Tus ("South Africa (Republic of _)"),
As_U.Tus ("Mali (Republic of _)"),
As_U.Tus ("Angola (Republic of _)"),
As_U.Tus ("Niger (Republic of _)"),
As_U.Tus ("Chad (Republic of _)"),
As_U.Tus ("Peru (Republic of _)"),
As_U.Tus ("Mongolia"),
As_U.Tus ("Iran (Persia) (Islamic Republic of _)"),
As_U.Tus ("Libya"),
As_U.Tus ("Sudan (Republic of the _)"),
As_U.Tus ("Indonesia (Republic of _)"),
As_U.Tus ("Federal District"),
As_U.Tus ("Tlaxcala"),
As_U.Tus ("Morelos"),
As_U.Tus ("Aguascalientes"),
As_U.Tus ("Colima"),
As_U.Tus ("Queretaro"),
As_U.Tus ("Hidalgo"),
As_U.Tus ("Mexico State"),
As_U.Tus ("Tabasco"),
As_U.Tus ("Nayarit"),
As_U.Tus ("Guanajuato"),
As_U.Tus ("Puebla"),
As_U.Tus ("Yucatan"),
As_U.Tus ("Quintana Roo"),
As_U.Tus ("Sinaloa"),
As_U.Tus ("Campeche"),
As_U.Tus ("Michoacan"),
As_U.Tus ("San Luis Potosi"),
As_U.Tus ("Guerrero"),
As_U.Tus ("Nuevo Leon (New Leon)"),
As_U.Tus ("Baja California"),
As_U.Tus ("Veracruz"),
As_U.Tus ("Chiapas"),
As_U.Tus ("Baja California Sur"),
As_U.Tus ("Zacatecas"),
As_U.Tus ("Jalisco"),
As_U.Tus ("Tamaulipas"),
As_U.Tus ("Oaxaca"),
As_U.Tus ("Durango"),
As_U.Tus ("Coahuila"),
As_U.Tus ("Sonora"),
As_U.Tus ("Chihuahua"),
As_U.Tus ("Greenland"),
As_U.Tus ("Saudi Arabia (Kingdom of _)"),
As_U.Tus ("Congo-Kinshasa (Democratic Republic of the Congo) (East Congo)"),
As_U.Tus ("Algeria (People's Democratic Republic of _)"),
As_U.Tus ("Kazakhstan (Republic of _)"),
As_U.Tus ("Argentina (Argentine Republic)"),
As_U.Tus ("Daman and Diu"),
As_U.Tus ("Dadra and Nagar Haveli (Dadra) (Nagar Haveli)"),
As_U.Tus ("Chandigarh"),
As_U.Tus ("Andaman and Nicobar (Andaman) (Nicobar)"),
As_U.Tus ("Lakshadweep"),
As_U.Tus ("Delhi (National Capital Territory of _)"),
As_U.Tus ("Meghalaya"),
As_U.Tus ("Nagaland"),
As_U.Tus ("Manipur"),
As_U.Tus ("Tripura"),
As_U.Tus ("Mizoram"),
As_U.Tus ("Sikkim"),
As_U.Tus ("Punjab"),
As_U.Tus ("Haryana"),
As_U.Tus ("Arunachal Pradesh"),
As_U.Tus ("Assam"),
As_U.Tus ("Bihar"),
As_U.Tus ("Uttarakhand"),
As_U.Tus ("Goa"),
As_U.Tus ("Kerala"),
As_U.Tus ("Tamil Nadu"),
As_U.Tus ("Himachal Pradesh"),
As_U.Tus ("Jammu and Kashmir (Jammu) (Kashmir)"),
As_U.Tus ("Chhattisgarh"),
As_U.Tus ("Jharkhand"),
As_U.Tus ("Karnataka"),
As_U.Tus ("Rajasthan"),
As_U.Tus ("Odisha (Orissa)"),
As_U.Tus ("Gujarat"),
As_U.Tus ("West Bengal"),
As_U.Tus ("Madhya Pradesh"),
As_U.Tus ("Telangana"),
As_U.Tus ("Andhra Pradesh"),
As_U.Tus ("Maharashtra"),
As_U.Tus ("Uttar Pradesh"),
As_U.Tus ("Puducherry"),
As_U.Tus ("New South Wales"),
As_U.Tus ("Australian Capital Territory"),
As_U.Tus ("Jervis Bay Territory"),
As_U.Tus ("Northern Territory"),
As_U.Tus ("South Australia"),
As_U.Tus ("Tasmania"),
As_U.Tus ("Victoria"),
As_U.Tus ("Western Australia"),
As_U.Tus ("Queensland"),
As_U.Tus ("Distrito Federal"),
As_U.Tus ("Sergipe"),
As_U.Tus ("Alagoas"),
As_U.Tus ("Rio de Janeiro"),
As_U.Tus ("Espirito Santo"),
As_U.Tus ("Rio Grande do Norte"),
As_U.Tus ("Paraiba"),
As_U.Tus ("Santa Catarina"),
As_U.Tus ("Pernambuco"),
As_U.Tus ("Amapa"),
As_U.Tus ("Ceara"),
As_U.Tus ("Acre"),
As_U.Tus ("Parana"),
As_U.Tus ("Roraima"),
As_U.Tus ("Rondonia"),
As_U.Tus ("Sao Paulo"),
As_U.Tus ("Piaui"),
As_U.Tus ("Tocantins"),
As_U.Tus ("Rio Grande do Sul"),
As_U.Tus ("Maranhao"),
As_U.Tus ("Goias"),
As_U.Tus ("Mato Grosso do Sul"),
As_U.Tus ("Bahia"),
As_U.Tus ("Minas Gerais"),
As_U.Tus ("Mato Grosso"),
As_U.Tus ("Para"),
As_U.Tus ("Amazonas"),
As_U.Tus ("District of Columbia (Washington, D.C.)"),
As_U.Tus ("Rhode Island"),
As_U.Tus ("Delaware"),
As_U.Tus ("Connecticut"),
As_U.Tus ("New Jersey"),
As_U.Tus ("New Hampshire"),
As_U.Tus ("Vermont"),
As_U.Tus ("Massachusetts (Commonwealth of _)"),
As_U.Tus ("Hawaii"),
As_U.Tus ("Maryland"),
As_U.Tus ("West Virginia"),
As_U.Tus ("South Carolina"),
As_U.Tus ("Maine"),
As_U.Tus ("Indiana"),
As_U.Tus ("Kentucky (Commonwealth of _)"),
As_U.Tus ("Tennessee"),
As_U.Tus ("Virginia (Commonwealth of _)"),
As_U.Tus ("Ohio"),
As_U.Tus ("Pennsylvania (Commonwealth of _)"),
As_U.Tus ("Mississippi"),
As_U.Tus ("Louisiana"),
As_U.Tus ("Alabama"),
As_U.Tus ("Arkansas"),
As_U.Tus ("North Carolina"),
As_U.Tus ("New York"),
As_U.Tus ("Iowa"),
As_U.Tus ("Illinois"),
As_U.Tus ("Georgia"),
As_U.Tus ("Wisconsin"),
As_U.Tus ("Florida"),
As_U.Tus ("Missouri"),
As_U.Tus ("Oklahoma"),
As_U.Tus ("North Dakota"),
As_U.Tus ("Washington"),
As_U.Tus ("South Dakota"),
As_U.Tus ("Nebraska"),
As_U.Tus ("Kansas"),
As_U.Tus ("Idaho"),
As_U.Tus ("Utah"),
As_U.Tus ("Minnesota"),
As_U.Tus ("Michigan"),
As_U.Tus ("Wyoming"),
As_U.Tus ("Oregon"),
As_U.Tus ("Colorado"),
As_U.Tus ("Nevada"),
As_U.Tus ("Arizona"),
As_U.Tus ("New Mexico"),
As_U.Tus ("Montana"),
As_U.Tus ("California"),
As_U.Tus ("Texas"),
As_U.Tus ("Alaska"),
As_U.Tus ("British Columbia"),
As_U.Tus ("Alberta"),
As_U.Tus ("Ontario"),
As_U.Tus ("Quebec"),
As_U.Tus ("Saskatchewan"),
As_U.Tus ("Manitoba"),
As_U.Tus ("Newfoundland and Labrador (Newfoundland) (Labrador)"),
As_U.Tus ("New Brunswick"),
As_U.Tus ("Nova Scotia"),
As_U.Tus ("Prince Edward Island"),
As_U.Tus ("Yukon"),
As_U.Tus ("Northwest Territories"),
As_U.Tus ("Nunavut"),
As_U.Tus ("India (Republic of _)"),
As_U.Tus ("Australia (Commonwealth of _)"),
As_U.Tus ("Brazil (Federative Republic of _)"),
As_U.Tus ("USA (United States of America) (America)"),
As_U.Tus ("Mexico (United Mexican States)"),
As_U.Tus ("Moscow"),
As_U.Tus ("Saint Petersburg"),
As_U.Tus ("Kaliningrad Oblast"),
As_U.Tus ("Ingushetia"),
As_U.Tus ("Adygea Republic"),
As_U.Tus ("North Ossetia-Alania Republic"),
As_U.Tus ("Kabardino-Balkar Republic"),
As_U.Tus ("Karachay-Cherkess Republic"),
As_U.Tus ("Chechen Republic (Chechnya) (Ichkeria)"),
As_U.Tus ("Chuvash Republic"),
As_U.Tus ("Ivanovo Oblast"),
As_U.Tus ("Lipetsk Oblast"),
As_U.Tus ("Oryol Oblast"),
As_U.Tus ("Tula Oblast"),
As_U.Tus ("Belgorod Oblast"),
As_U.Tus ("Vladimir Oblast"),
As_U.Tus ("Kursk Oblast"),
As_U.Tus ("Kaluga Oblast"),
As_U.Tus ("Tambov Oblast"),
As_U.Tus ("Bryansk Oblast"),
As_U.Tus ("Yaroslavl Oblast"),
As_U.Tus ("Ryazan Oblast"),
As_U.Tus ("Astrakhan Oblast"),
As_U.Tus ("Moscow Oblast"),
As_U.Tus ("Smolensk Oblast"),
As_U.Tus ("Dagestan Republic"),
As_U.Tus ("Voronezh Oblast"),
As_U.Tus ("Novgorod Oblast"),
As_U.Tus ("Pskov Oblast"),
As_U.Tus ("Kostroma Oblast"),
As_U.Tus ("Stavropol Krai"),
As_U.Tus ("Krasnodar Krai"),
As_U.Tus ("Kalmykia Republic"),
As_U.Tus ("Tver Oblast"),
As_U.Tus ("Leningrad Oblast"),
As_U.Tus ("Rostov Oblast"),
As_U.Tus ("Volgograd Oblast"),
As_U.Tus ("Vologda Oblast"),
As_U.Tus ("Murmansk Oblast"),
As_U.Tus ("Karelia Republic"),
As_U.Tus ("Nenets Autonomous Okrug"),
As_U.Tus ("Komi Republic"),
As_U.Tus ("Arkhangelsk Oblast"),
As_U.Tus ("Mordovia Republic"),
As_U.Tus ("Nizhny Novgorod Oblast"),
As_U.Tus ("Penza Oblast"),
As_U.Tus ("Kirov Oblast"),
As_U.Tus ("Mari El Republic"),
As_U.Tus ("Orenburg Oblast"),
As_U.Tus ("Ulyanovsk Oblast"),
As_U.Tus ("Perm Krai"),
As_U.Tus ("Bashkortostan Republic"),
As_U.Tus ("Udmurt Republic"),
As_U.Tus ("Tatarstan Republic"),
As_U.Tus ("Samara Oblast"),
As_U.Tus ("Saratov Oblast"),
As_U.Tus ("Yamalo-Nenets"),
As_U.Tus ("Khanty-Mansi"),
As_U.Tus ("Sverdlovsk Oblast"),
As_U.Tus ("Tyumen Oblast"),
As_U.Tus ("Kurgan Oblast"),
As_U.Tus ("Chelyabinsk Oblast"),
As_U.Tus ("Buryatia Republic"),
As_U.Tus ("Zabaykalsky Krai"),
As_U.Tus ("Irkutsk Oblast"),
As_U.Tus ("Novosibirsk Oblast"),
As_U.Tus ("Tomsk Oblast"),
As_U.Tus ("Omsk Oblast"),
As_U.Tus ("Khakassia Republic"),
As_U.Tus ("Kemerovo Oblast"),
As_U.Tus ("Altai Republic"),
As_U.Tus ("Altai Krai"),
As_U.Tus ("Tuva Republic"),
As_U.Tus ("Krasnoyarsk Krai"),
As_U.Tus ("Magadan Oblast"),
As_U.Tus ("Chukotka Okrug"),
As_U.Tus ("Kamchatka Krai"),
As_U.Tus ("Sakhalin Oblast"),
As_U.Tus ("Primorsky Krai"),
As_U.Tus ("Jewish Autonomous Oblast"),
As_U.Tus ("Khabarovsk Krai"),
As_U.Tus ("Amur Oblast"),
As_U.Tus ("Sakha Republic (Yakutia Republic)"),
As_U.Tus ("Canada"),
As_U.Tus ("Russia (Russian Federation)"),
As_U.Tus ("Shanghai Municipality"),
As_U.Tus ("Tianjin Municipality"),
As_U.Tus ("Beijing Municipality"),
As_U.Tus ("Hainan Province"),
As_U.Tus ("Ningxia Hui Autonomous Region"),
As_U.Tus ("Chongqing Municipality"),
As_U.Tus ("Zhejiang Province"),
As_U.Tus ("Jiangsu Province"),
As_U.Tus ("Fujian Province"),
As_U.Tus ("Anhui Province"),
As_U.Tus ("Liaoning Province"),
As_U.Tus ("Shandong Province"),
As_U.Tus ("Shanxi Province"),
As_U.Tus ("Jiangxi Province"),
As_U.Tus ("Henan Province"),
As_U.Tus ("Guizhou Province"),
As_U.Tus ("Guangdong Province"),
As_U.Tus ("Hubei Province"),
As_U.Tus ("Jilin Province"),
As_U.Tus ("Hebei Province (Yanzhao Province)"),
As_U.Tus ("Shaanxi Province"),
As_U.Tus ("Nei Mongol Autonomous Region (Inner Mongolia)"),
As_U.Tus ("Heilongjiang Province"),
As_U.Tus ("Hunan Province"),
As_U.Tus ("Guangxi Zhuang Autonomous Region"),
As_U.Tus ("Sichuan Province"),
As_U.Tus ("Yunnan Province"),
As_U.Tus ("Xizang Autonomous Region (Tibet)"),
As_U.Tus ("Gansu Province"),
As_U.Tus ("Qinghai Province (Tsinghai Province)"),
As_U.Tus ("Xinjiang Uyghur Autonomous Region"),
As_U.Tus ("China (People's Republic of _)"),
As_U.Tus ("United States Minor Outlying Islands"),
As_U.Tus ("Clipperton Island"),
As_U.Tus ("Antarctica"),
As_U.Tus ("International (Worldwide) (Earth)"),
As_U.Tus ("?"));
end Ctrynams;

