#!/bin/bash

# Error message and usage
function error {
  echo "ERROR: $1." 1>&2
  echo "Usage: `basename $0` <target_dir>" 1>&2
  exit 1
}
  
# Check arguments
if [ -z "$1" ] ; then
  error "Missing argument"
fi
export TARGET=$1
if [ \( ! -d $TARGET \) -o \( ! -w $TARGET \) ] ; then
  error "Directory $TARGET not found or not writable"
fi

# Generate the version for export
make Export

# Files to export
export FILES="as_u.adb as_u.ads bits.adb bits.ads ctrynams.ads \
ctrynams_short.ads mapcodes.adb mapcodes.ads ndata.ads \
str_tools.adb str_tools.ads t_mapcode.adb"

# Add Copyright headers and copy in TARGET
H[1]='------------------------------------------------------------------------------'
H[2]=' Copyright (C) 2014-2015 Stichting Mapcode Foundation (http://www.mapcode.com)'
H[3]=' '
H[4]=' Licensed under the Apache License, Version 2.0 (the "License");'
H[5]=' you may not use this file except in compliance with the License.'
H[6]=' You may obtain a copy of the License at'
H[7]=' '
H[8]='    http://www.apache.org/licenses/LICENSE-2.0'
H[9]=' '
H[10]=' Unless required by applicable law or agreed to in writing, software'
H[11]=' distributed under the License is distributed on an "AS IS" BASIS,'
H[12]=' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.'
H[13]=' See the License for the specific language governing permissions and'
H[14]=' limitations under the License.'
H[15]='------------------------------------------------------------------------------'

for file in $FILES ; do
  echo $file
  i=1
  # Prepend comment
  comment='--'
  while [ ! -z "${H[i]}" ] ; do
    line=$comment${H[i]}
    if [ $i -eq 1 ] ; then
      # First line
      echo $line > $TARGET/$file
    else
      echo $line >> $TARGET/$file
    fi
    i=$(( i + 1 ))
  done
  # Append file
  echo >> $TARGET/$file
  cat $file >> $TARGET/$file
done

