#!/bin/bash

echo Encode
while read -r lat lon || [[ -n "$lat" ]]; do
  if [ \( -z "$lat" \) -o \( "$lat" = "#" \) ] ; then
    continue
  fi
  t_accuracy $lat $lon >/dev/null
  res=$?
  if [ $res -ne 0 ] ; then
    if [ $res -eq 1 ] ; then
      exit 1
    fi
  fi
done < EncodeOk.txt

echo Decode
let L=0
while read -r ctx cod lat lon loc glob || [[ -n "$ctx" ]]; do
  if [ \( -z "$ctx" \) -o \( "$ctx" = "#" \) ] ; then
    continue
  fi
  t_accuracy $ctx:$cod >/dev/null
  res=$?
  if [ $res -ne 0 ] ; then
    if [ $res -eq 1 ] ; then
      exit 1
    fi
  fi

  R=$((L % 100))
  if [ $R -eq 0 ] ; then
    echo -n "."
  fi
  let L=$L+1

done < DecodeOk.txt
echo

echo "Done."
