include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(REPOSIT)
ADACTL := true

AFPX := true
AFPX_XREF := afpx_xref

SUBUNITS := menu2.menu21 resol.r_compute
EXES := approxp

CLIBS := $(X11_SLIBS)

include $(TEMPLATES)/ada.mk

