include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(REPOSIT)
ADACTL := true

SUBUNITS := sok_manager.sok_file sok_manager.sok_menu
EXES := sokoban scores

CLIBS := $(X11_SLIBS)

include $(TEMPLATES)/ada.mk

