include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(REPOSIT)

EXES := sensor

CLIBS := $(PCRE_SLIBS)

LARGS_sensor.stat := $(PCRE_ALIBS)

TXT := Sensor
DOCOPTS_Agite= -a toc

include $(TEMPLATES)/ada.mk

