#!/bin/bash
if [ \( "$SENSOR_DEBUG" = "Y" \) -o \( "$SENSOR_DEBUG" = "YES" \) ] ; then
  export DEBUG=1
else
  export DEBUG=0
fi

if [ $DEBUG -eq 1 ] ; then
  export sensor_TRACE_Sensor=Debug
  export sensor_TRACEFILE=Sensor.log
fi

# Env
export INPUT=input.txt
export OUTPUT=output.txt
export EXPECTED=expected.txt
export DETAILS=details.txt
export TIMEOUT=1
export PERIOD="0.2"
export TRIGGER="Trigger"

# Clean files
function cleanup {
  rm -f $INPUT $OUTPUT $EXPECTED $DETAILS
}
trap 'echo "Aborted"; cleanup; exit 1' SIGINT SIGTERM

if [ "$1" = "clean" ]  ; then
  cleanup
  exit 0
fi

# Option verbose
export VERBOSE=1
if [ \( "$1" = "-s" \) -o \( "$1" = "--silent" \) ] ; then
  VERBOSE=0
  shift
fi

# Output if verbose
function output {
  if [ $VERBOSE -eq 1 ] ; then
    echo $*
  fi
}

# Check empty config file
output "Check empty config file"
./sensor -c Empty.xml
if [ $? -ne 0 ] ; then
  echo "Error when checking empty config file." 1>&2
  exit 1
fi

# Initialise input and output
echo -e "Toto\nTiti\nTata\n${TRIGGER} 1\nToto\n" > $INPUT
rm -f $OUTPUT
touch $OUTPUT

# Start sensor
output "Starting"
./sensor Test.xml &
export SENSOR_PID=$!

# Scenario
sleep $TIMEOUT
output "Adding a trigger"
echo -e "Tata\nTate\n${TRIGGER} 2\nTati\n" >> $INPUT
sleep $TIMEOUT
# Two triggers that will be extracted together
output "Adding two triggers"
echo -e "Teta\nTete\n${TRIGGER} 3\nTeti\n" >> $INPUT
sleep $PERIOD
sleep $PERIOD
echo -e "Tita\nTite\n${TRIGGER} 4\nTiti\n" >> $INPUT
sleep $TIMEOUT
# This one will be filtered out by the latency
output "Adding a trigger"
echo -e "${TRIGGER} 4\n" >> $INPUT
sleep $TIMEOUT
output "Adding a trigger"
echo -e "Tota\nTote\n${TRIGGER} 5\nToti\n" >> $INPUT
sleep $TIMEOUT

# Terminate
output "Terminating"
kill $SENSOR_PID

# Check
cat >$EXPECTED <<EOF
Got >${TRIGGER} 1
<
Got >${TRIGGER} 2
<
Got >${TRIGGER} 3
${TRIGGER} 4
<
Repeated LogTrigger
Got >${TRIGGER} 5
<
EOF
cmp $OUTPUT $EXPECTED 2>/dev/null
res=$?
if [ $res -ne 0 ] ; then
  echo "File $OUTPUT differs from expected $EXPECTED." 1>&2
  exit 1
fi

cat >${DETAILS} <<EOF
Got >${TRIGGER} 1
<
Got >${TRIGGER} 2
<
Got >${TRIGGER} 3
${TRIGGER} 4
<
Got >${TRIGGER} 5
<
Got >${TRIGGER} 1
<
Got >${TRIGGER} 2
<
Got >${TRIGGER} 3
${TRIGGER} 4
<
Got >${TRIGGER} 5
<
Got >${TRIGGER} 1
<
Got >${TRIGGER} 2
<
Got >${TRIGGER} 3
${TRIGGER} 4
<
Got >${TRIGGER} 5
<
EOF
cmp $OUTPUT $EXPECTED 2>/dev/null
res=$?
if [ $res -ne 0 ] ; then
  echo "File $OUTPUT differs from expected $EXPECTED." 1>&2
  exit 1
fi

# Cleanup
echo Test OK.
if [ $DEBUG -eq 0 ] ; then
  cleanup
fi

