with COMMON, FILE;
pragma ELABORATE(FILE);
package DATA is
  NB_COTE : constant COMMON.COTE_RANGE := FILE.GET_NB_COTE;

  MANUFAS : constant COMMON.MANUFA_ARRAY := FILE.GET_MANUFA;
  DESIGNS : constant COMMON.DESIGN_ARRAY := FILE.GET_DESIGN;

  subtype EFF_COTE_RANGE is COMMON.COTE_RANGE range 1 .. NB_COTE;
  subtype EFF_LINE_RANGE is COMMON.LINE_RANGE range 1 .. NB_COTE + 1;

end DATA;
