with MY_IO;
with COMMON, RESOLUTION, DISPLAY;
procedure SIMUSI is

begin
  DISPLAY.PRINT_TITTLE(COMMON.MANUFA);
  RESOLUTION.SOLVE (COMMON.MANUFA);

  DISPLAY.PRINT_TITTLE(COMMON.DESIGN);
  RESOLUTION.SOLVE (COMMON.DESIGN);

  DISPLAY.PRINT_RESULT;

exception
  when RESOLUTION.ABORT_ERROR =>
    DISPLAY.PRINT_RESULT;
end SIMUSI;

