include $(HOME)/Makefiles/common.mk

ADAVIEW := $(REPOSIT)

NOTUNITS := test
EXES := astub

CLIBS := cutil
CLIBS_astub := posix2pcre pcre

TXT := Astub
DOCOPTS_Astub := -a toc

include $(TEMPLATES)/ada.mk

