include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(REPOSIT)

NOTUNITS := test
EXES := astub

CLIBS := cutil
CLIBS_astub := $(PCRE_SLIBS)

TXT := Astub
DOCOPTS_Astub := -a toc

include $(TEMPLATES)/ada.mk

