#!/bin/bash
function clean {
  rm -f test.ads test.adb test.o test.ali
}
trap 'echo ""; clean; exit 1' SIGINT SIGTERM

if [ -f test.adb ] ; then
  echo "Removing previous test.adb"
  clean
fi
ln -s test.ads.ref test.ads
make test.adb
if [ $? -ne 0 ] ; then
  exit 1
fi
cmp -s test.adb test.adb.ref
res=$?
if [ $res -eq 1 ] ; then
  echo "Error: Files differ."
  tkdiff test.adb.ref test.adb
  exit 1
elif [ $res -ne 0 ] ; then
  echo "An error occured while comparing."
  exit 1
fi

gnatmake test.adb >/dev/null 2>&1
if [ $? -ne 0 ] ; then
  echo "Error: test.adb does not compile"
  exit 1
fi
clean
echo Ok.
exit 0

