#!/bin/bash
# Agrep: invoque asusbt to grep

type asubst > /dev/null 2>&1
res=$?
if [ $res -eq 1 ] ; then
  echo "Error, program asubst not found. Abort."  >&2
  exit 3
fi

# Help or version
if [ $# -eq 1 ] ; then
  if [ \( "$1" = "-h" \) -o \( "$1" = "--help" \) ] ; then
    echo "Usage: `basename $0` [ -l | --line ] [ -i | --ignorecase ] [ { <file> } ]" >&2
    echo "    or `basename $0` -V | --version" >&2
    exit 2
  elif [ \( "$1" = "-V" \) -o \( "$1" = "-h" \) ] ; then
    echo "agrep "`asubst -V 2>&1 | cut -d " " -f 2` >&2
    exit 2
  fi
fi

# Options
export opt=""
while [ "$1" != "" ] ; do
 case "$1" in
    "-l" | "--line")
      opt="$opt $1"
      shift
    ;;
    "-i" | "--ignorecase")
      opt="$opt $1"
      shift
    ;;
    *)
     break
    ;;
  esac
done

# Find pattern
export find=$1
shift

# Invoke asubst
exec asubst -g $opt "$find" "" $*

