#!/bin/bash
# set -vx
while true ; do
  # Read line until end of file
  read input search replace expected
  if [ $? -ne 0 ] ; then
    break
  fi
  # Skip empty lines and comments
  if [ "$input" = "" ] ; then
    continue
  fi
  c=`echo $input | cut -c1`
  if [ "$c" = "#" ]; then
    continue
  fi
  # remove '"'s
  input="`echo $input | cut -d '"' -f2`"
  search="`echo $search | cut -d '"' -f2`"
  replace="`echo $replace | cut -d '"' -f2`"
  expected="`echo $expected | cut -d '"' -f2`"
  # Do test
  echo "echo $input | asubst \"$search\" \"$replace\" -> $expected"
  export result=`echo -e -n $input | asubst "$search" "$replace"`
  # Check result is expected
  if [ "$result" != "$expected" ] ; then
    echo "Error: expected $expected != got $result"
    exit 1
  fi
done
echo Done.
exit 0

