#!/bin/bash
# Display current version
type asubst
asubst --version

# Play scenario
./player Scenario
if [ $? -ne 0 ] ; then
  echo "Scenario failed."
  exit 1
fi
echo "Test scenario, OK."

# Various file names, reference (in), expected result
#  tested (in/out), list, saved
export FR=tstfile.ref
export FE=tstfile.exp
export FT=tstfile.tst
export FL=tstfile.lst
export FS=tstfile.tst.asu

# Initial cleanup of files
rm -rf $FS Temp_File.*

# Make reference in file and result
# Will remove both "------" and the linefeed before Test
echo "Package body Pack is" > $FR
echo "Package body Pack is" > $FE
echo "" >> $FR
echo "" >> $FE
echo "  ----------" >> $FR
echo "  -- Test --" >> $FR
echo "  -- Test --" >> $FE
echo "  ----------" >> $FR
echo "" >> $FR
echo "  procedure Test is" >> $FR
echo "  procedure Test is" >> $FE
echo "  begin" >> $FR
echo "  begin" >> $FE
echo "    null" >> $FR
echo "    null" >> $FE
echo "  end T;" >> $FR
echo "  end T;" >> $FE
echo "" >> $FR
echo "" >> $FE
echo "end Pack;" >> $FR
echo "end Pack;" >> $FE

# Substit from file list with no backup
cp $FR $FT
echo $FT > $FL
res=`asubst -f "^(  )*--.*\n(  )*--.*\n(  )*--.*\n\n" "\R03\n" $FL`
code=$?
# Check exit code and that result is expected
if [ $code -ne 0 ] ; then
  echo "Error: asubst exited with code $code"
  exit 1
fi
cmp -s $FT $FE
if [ $? -ne 0 ] ; then
  echo "Result file $FT differs from expected $FE."
  exit 1
fi
if [ "$res" != "$FT" ] ; then
  echo "Asubst generated wrong output $res. Expected $FT."
  exit 1
fi
if [ -f $FS ] ; then
  echo "Unexpected backup $FS found."
  exit 1
fi
echo "File substitution from file list and with no backup, OK."

# Substit with backup
rm -rf $FS
cp $FR $FT
res=`asubst -s "^(  )*--.*\n(  )*--.*\n(  )*--.*\n\n" "\R03\n" $FT`
code=$?
# Check exit code and result is expected
if [ $code -ne 0 ] ; then
  echo "Error: asubst exited with code $code"
  exit 1
fi
cmp -s $FT $FE
if [ $? -ne 0 ] ; then
  echo "Result file $FT differs from expected $FE."
  exit 1
fi
if [ "$res" != "$FT" ] ; then
  echo "Asubst generated wrong output $res. Expected $FT."
  exit 1
fi
if [ ! -f $FS ] ; then
  echo "Backup file $FS not found."
  exit 1
fi
cmp -s $FS $FR
if [ $? -ne 0 ] ; then
  echo "Backup file $FS differs from reference $FR."
  exit 1
fi
if [ -f "Temp_File.*" ] ; then
  echo "Found remaining temorary files " Temp_File.* "."
  exit 1
fi
echo "File substitution with backup, OK."

# Cleanup test files
rm -rf $FR $FT $FS $FE $FL

