include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(REPOSIT)

SUBUNITS := action-treat_click action-treat_release
EXES := mmind

CLIBS_mmind := $(X11_SLIBS)

include $(TEMPLATES)/ada.mk

