with CON_IO;
procedure T_COLOR is
  C : CHARACTER;
begin
  CON_IO.INIT;
  CON_IO.SET_BACKGROUND (CON_IO.BROWN);

  loop
    CON_IO.SET_FOREGROUND(CON_IO.DEFAULT_FOREGROUND);
    CON_IO.CLEAR;
    for I in CON_IO.EFFECTIVE_COLORS loop
      CON_IO.MOVE (CON_IO.COLORS'POS(I), 1);
      CON_IO.PUT (CON_IO.EFFECTIVE_COLORS'IMAGE(I) );
      CON_IO.MOVE (CON_IO.COLORS'POS(I), 20);
      CON_IO.PUT ('!', FOREGROUND => I, MOVE => FALSE);
      CON_IO.NEW_LINE;
    end loop;

    CON_IO.SET_FOREGROUND(CON_IO.GET_BACKGROUND);
    CON_IO.MOVE;
    C := CON_IO.GET;
    exit when C /= ASCII.NUL;
  end loop;
  CON_IO.DESTROY;

end T_COLOR;

