with CON_IO;
procedure T_COLOR is
begin
  CON_IO.INIT;
  CON_IO.SET_BACKGROUND (CON_IO.BROWN);
  CON_IO.CLEAR;

  for I in CON_IO.EFFECTIVE_COLORS loop
    CON_IO.MOVE (CON_IO.COLORS'POS(I), 1);
    CON_IO.PUT (CON_IO.EFFECTIVE_COLORS'IMAGE(I) );
    CON_IO.MOVE (CON_IO.COLORS'POS(I), 20);
    CON_IO.PUT ('!', FOREGROUND => I, MOVE => FALSE);
    CON_IO.NEW_LINE;
  end loop;

  CON_IO.PAUSE;
  CON_IO.MOVE (CON_IO.POSITION);
end T_COLOR;

