include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(REPOSIT)

EXES := fourtwentyone

CLIBS := cutil
CLIBS_als := posix2pcre pcre

TXT := FourTwentyOne

include $(TEMPLATES)/ada.mk

