include $(HOME)/Makefiles/common.mk

ADAVIEW := $(HOME)/ada/cots/pragmarc

EXES := assertst bag_test bs_test calc cmplxtst datetest devil devil2 df_test \
        evolve_pi gcd_test hashtest heap_test lasgn lb_test lin_test \
        line_fit_test lsort mat_test mathtest mt q_test qb_test \
        qs_test radix_test randtest reflect_test set_test skiptest sp_test \
        strm_sub test_images wrapping_test xor_problem

include $(TEMPLATES)/ada.mk

