#!/bin/bash
# set -vx

export ENIGMA_CONF_FILE=../enigma.xml

# For loops
export LIST="A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"

# Do local tests with: settings, encypted and decoded text
echo "Test of fixed settings, encrypted and decoded files:"
for i in 1 2 3 4 ; do
  cat crypt${i} | enigma `tail -1 set${i}` > tmp
  cmp -s decod${i} tmp
  res=$?
  echo -n "cat crypt${i} | enigma `tail -1 set${i}` "
  if [ $res -eq 0 ] ; then
    echo "OK."
  else
    echo "KO."
    rm -f tmp
    echo "FAILED."
    exit 1
  fi
done
rm tmp
echo ""

# Verify upper level txt files through enigmacode -c then -d
echo "Test of txt files with enigmacode:"
for file in ../*.txt ; do
  cat $file | enigmacode -c > tmpc
  cat tmpc | enigmacode -d > tmpd
  cmp -s $file tmpd
  res=$?
  echo -n "`basename $file` through enigmacode -c then -d "
  if [ $res -eq 0 ] ; then
    echo "OK."
  else
    echo "KO."
    rm -f tmpc tmpd
    echo "FAILED."
    exit 1
  fi
done
rm tmpc tmpd
echo ""

# Verify several letters twice through random setting
echo "Test of  a letter twice through a random setting:"
for L in $LIST ; do
  key=`def_enigma rnd`
  r=`echo -n $L | enigma $key`
  r=`echo -n $r | enigma $key`
  echo -n "$L through $key twice "
  if [ "$r" = "$L" ] ; then
    echo "OK."
  else
    echo "KO."
    echo "FAILED."
    exit 1
  fi
done
echo ""

# Verify key <-> text conversion
echo "Test of key to text and back:"
for L in $LIST ; do
  key1="`def_enigma rnd`"
  text=`def_enigma -text $key1 | awk '{print $NF}'`
  key2="`def_enigma $text`"
  echo -n "$key1 to text and reverse "
  if [ "$key1" = "$key2" ] ; then
    echo "OK."
  else
    echo "KO."
    echo "FAILED."
    exit 1
  fi
done
echo ""

# Verfiy text <-> key conversion
echo "Test of text to key and back:"
for L in $LIST ; do
  text1=`def_enigma -text rnd | awk '{print $NF}'`
  key="`def_enigma $text1`"
  text2=`def_enigma -text $key | awk '{print $NF}'`
  echo -n "$text1 to key and reverse "
  if [ "$text1" = "$text2" ] ; then
    echo "OK."
  else
    echo "KO."
    echo "FAILED."
    exit 1
  fi
done
echo ""

echo Completed OK.
exit 0

