include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(REPOSIT)
ADACTL := true

EXES := dictio t_dictio

CLIBS := $(PCRE_SLIBS) $(UTILS_SLIBS)

include $(TEMPLATES)/ada.mk

