#!/bin/bash

export DICTIO_DEBUG=Y

if [ "$DICTIO_DEBUG" = "Y" ] ; then
# These ones generate few traces
export DICTIO_DEBUG_STATUS=Y
export DICTIO_DEBUG_FIGHT=Y
export DICTIO_DEBUG_SYNC=Y
export DICTIO_DEBUG_ONLINE=Y
export DICTIO_DEBUG_CLIENT=Y
fi

# These ones generate many traces
#export DICTIO_DEBUG_CLIENT_DATA=Y
#export DICTIO_DEBUG_CLIENT_NOTIFY=Y
#export DICTIO_DEBUG_INTRA=Y

# These ones are not debug
# Flow control on LAN during sync
export DICTIO_DELAY_PER_KB=0.010
# Delay after which master is stable
export DICTIO_STABLE_DELAY=0.200
# Default prio
export DICTIO_PRIO=10
# Default mode
export MODE=bus

# Parse args
while [ "$1" != "" ] ; do
  if [ "$1" = "-p" ] ; then
    shift
    export DICTIO_PRIO=$1
    shift
  elif [ "$1" = "-b" ] ; then
    export MODE=bus
    shift
  elif [ "$1" = "-c" ] ; then
    export MODE=channel
    shift
  else
    echo "Usage: `basename $0`   -b | -c   [-p <prio> ]"
    exit 1
  fi
done

if [ "$MODE" = "channel" ] ; then
  export CHANNEL="-ntest_tcp -cdictio.chn"
else
  export CHANNEL="-ntest_udp -btest_ipm"
fi

export HOST=`uname -s`
if [ "$HOST" = "Linux" ] ; then
  export PORT=fido
elif [ "$HOST" = "OSF1" ] ; then
  export PORT=rdg
else
  echo "Unknown host type: $HOST"
  exit 1
fi

exec ./dictio $CHANNEL -p$PORT -P$DICTIO_PRIO
# gvd ./dictio --pargs $CHANNEL -p$PORT -P$DICTIO_PRIO

