#!/bin/bash
export Src=/usr/local/account/data
export Dst=/aux/account
export Rep=/root/GIT/account
if [ \( -d $Src \) -a \( -d $Dst \) ] ; then
  /bin/cp -r $Src $Dst
fi
if [ \( -d $Rep \) -a \( -d $Dst \) ] ; then
  /bin/cp -r $Rep $Dst/GIT
fi

