include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(USR)/dictio $(REPOSIT)
ADACTL := true

EXES := t_fifos

CLIBS := $(UTILS_SLIBS)

include $(TEMPLATES)/ada.mk

