include $(HOME)/Makefiles/common.mk

include $(HOME)/Makefiles/units.mk

ADAVIEW := $(REPOSIT)
AFPX := true
EXES := $(UNITS)

CLIBS := x_mng cutil X11
CLIBS_t_ndbm := cndbm

include $(TEMPLATES)/ada.mk

