#!/bin/bash

# Put errno codes, names and erro text

# Create a c source that includes errno.h
export FILE=t_str_error.c
cat << EOF > $FILE
#include "errno.h"
int main (void) {
  return 0;
}
EOF
# Preprocess source file and filter "#define NAME code" or "#define NAME NAME"
# Put definitions and aliases
cpp -dD $FILE | asubst -g "^#define (E[A-Z]+)[\B]+([0-9]+|E[A-Z]+)$" "\r12 \r11" | t_str_error
# Cleanup
rm $FILE

