#!/bin/bash

if [ \( "$1" = "-h" \) -o \( "$1" = "--help" \) ] ; then
  echo "Usage: `basename $0` [ <nb_fields> ]"
  exit 1
fi

function error {
  echo "ERROR $1" >&2
  exit 1
}

nb=""
let nbn=1
if [ "$1" != "" ] ; then
  nb=$1
  let nbn=0+$1
fi

if false ; then

echo Insertions and deletions
let dscr=1
while true ; do

  echo ""
  echo "Dscr $dscr"

  let field=0

  while true ; do

    echo "Field $field"

    # Insert fields
    afpx_rnb -o Afpx.tmp -D $dscr -i $field $nb 2>err
    if [ $? -ne 0 ] ; then
      err=`cat err`
      crit="ERROR: Field [0-9]+ does not exist in descriptor [0-9]+."
      if [[ $err =~ $crit ]] ; then
        break
      else
        error "inserting field $field: $err"
      fi
    fi

    # Delete fields
    let field=$field+1
    afpx_rnb -f Afpx.tmp -o Afpx.res -D $dscr -d $field $nb 2>err
    if [ $? -ne 0 ] ; then
      err=`cat err | sed 's/\n//g'`
      error "deleting field $field: $err"
    fi

    # Check that result is unchanged
    cmp Afpx.xml Afpx.res > /dev/null 2>&1
    if [ $? -ne 0 ] ; then
      error "file Afpx.res differs from original Afpx.xml"
    fi

  done

  let dscr=$dscr+1

  # Skip hole or exit
  if [ $dscr -eq 5 ] ; then
    let dscr=6
  elif [ \( $dscr -ge 11 \) -a \( $dscr -le 14 \) ] ; then
    let dscr=15
  elif [ $dscr -eq 19 ] ; then
    break
  fi
done
fi

type asubst > /dev/null 2>&1
if [ $? -ne 0 ] ; then
  error "asubst not found"
fi

echo "Move nums then back"
cat Afpx.xml | asubst -q -D "" '\n([\B]*\n)+' '\n' > Afpx.ref
for nums in 1:7 2:8 3:9 16:8 ; do

  # Movement back
  let bnumi=`echo $nums | cut -d ':' -f 1`+0
  let bnumj=`echo $nums | cut -d ':' -f 2`+0
  if [ $bnumi -lt $bnumj ] ; then
    # We moved nb from bnumi to bnumj above
    # Move back from bnumj-nb+1 to bnumi - 1
    let bnumi=$bnumi-1
    let bnumj=$bnumj-$nbn+1
  else
     # We moved nb from bnumi to bnumj below
     # Move back from bnumj to bnumi+nb
     let bnumi=$bnumi
     let bnumj=$bnumj+$nbn
  fi
  bnums=$bnumj":"$bnumi

  echo "$nums then $bnums"
  # Move fields
  afpx_rnb -o Afpx.tmp -D 1 -m $nums $nb 2>err
  if [ $? -ne 0 ] ; then
    err=`cat err | sed 's/\n//g'`
    error "moving fields $nums: $err"
  fi

  # Move back
  afpx_rnb -f Afpx.tmp -o Afpx.res -D 1 -m $bnums $nb 2>err
  if [ $? -ne 0 ] ; then
    err=`cat err | sed 's/\n//g'`
    error "moving field $bnums: $err"
  fi
  asubst -q -D "" '\n([\B]*\n)+' '\n' Afpx.res

  # Check that result is unchanged
  cmp Afpx.ref Afpx.res > /dev/null 2>&1
  if [ $? -ne 0 ] ; then
    error "file Afpx.res differs from reference Afpx.ref"
  fi

done

rm -f err Afpx.ref Afpx.tmp Afpx.res
echo "Test Ok."

