#!/bin/bash

# Test appp
VERBOSE=0
if [ "$1" = "-v" ] ; then
  VERBOSE=1
fi

export APP=../../reposit/app

# Input/output/error files, obtained and expected
export IN_FILE=t_app.in
export OUT_FILE=t_app.out
export EXPOUT_FILE=expected.out
export ERR_FILE=t_app.err
export EXPERR_FILE=expected.err

# Say something if verbose
function say {
  if [ $VERBOSE -eq 1 ] ; then
    echo $*
  fi
}

# Compare 2 files
function comp {
  cmp $1 $2 2> /dev/null
  res=$?
  if [ $res -ne 0 ] ; then
    echo "File $1 differs from expected $2." 1>&2
    exit 1
  fi
}

# One try with some definitions
function try {
  $APP $* <$IN_FILE >$OUT_FILE 2>$ERR_FILE
  comp $ERR_FILE $EXPERR_FILE
  comp $OUT_FILE $EXPOUT_FILE
}

# Prepare input and empty error
cat <<EOF >$IN_FILE
  #IfDef X
    echo "Def X"
    #Define DefX
    #Define DefY ValY
  #ElsifNotDef Y&Z
    echo "NotDef Y&Z"
  #ElsifDef T
    echo "Def T"
    #IfNotDef A
      echo "NotDef A"
    #ElsifDef B|C
      echo "Def B|C"
      echo "B is "
#RefDef B
    #ElseDef
      echo "Def A NotDef A|B|C"
    #EndifDef
  #EndifDef
#RefDef DefX
#RefDef DefY
EOF

echo -n "" >$EXPERR_FILE

# With no def
cat <<EOF >$EXPOUT_FILE
    echo "NotDef Y&Z"


EOF
try 
say "No def OK"

# With a def for IfDef
cat <<EOF >$EXPOUT_FILE
    echo "Def X"

ValY
EOF
try X
say "X OK"
try X Y
say "X Y OK"
try X T
say "X T OK"
try X Y T
say "X Y T OK"

# With a def for ElsifNotDef 
cat <<EOF >$EXPOUT_FILE


EOF
try Y
say "Y OK"
try Z
say "Z OK"
try Y Z
say "Y Z OK"

# With a def for ElsifDef 
# With no def for IfNotDef
cat <<EOF >$EXPOUT_FILE
    echo "Def T"
      echo "NotDef A"


EOF
try Y T
say "Y T OK"

# With a def for IfNotDef
cat <<EOF >$EXPOUT_FILE
    echo "Def T"
      echo "Def A NotDef A|B|C"


EOF
try Y T A
say "Y T A OK"

# With a def for ElsifDef
cat <<EOF >$EXPOUT_FILE
    echo "Def T"
      echo "Def B|C"
      echo "B is "



EOF
try Y T A B
say "Y T A B OK"
try Y T A C
say "Y T A C OK"
try Y T A B C
say "Y T A B C OK"

# With a def set for ElsifDef
cat <<EOF >$EXPOUT_FILE
    echo "Def T"
      echo "Def B|C"
      echo "B is "
Bset


EOF
try Y T A B=Bset
say "Y T A Bset OK"
try Y T A B=Bset C
say "Y T A Bset C OK"

rm $IN_FILE $OUT_FILE $EXPOUT_FILE $ERR_FILE $EXPERR_FILE
echo OK

