#!/bin/bash

if [ \( -z "$1" \) -o \( "$1" = "-h" \) -o \( "$1" = "--help" \) ] ; then
  echo "Usage: `basename $0` [ -i <interval> ] { <file> }" 1>&2
  exit 1
fi

delay=10
if [ "$1" = "-i" ] ; then
  delay=$2
  shift
  shift
fi

# Cat all arguments, one each <delay> sec

while [ -n "$1" ] ; do
  echo $1 1>&2
  cat $1
  shift
  if [ -z "$1" ] ; then
    break
  fi
  sleep $delay
done

