include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(REPOSIT)

AFPX := true
AFPX_XREF := afpx_xref

EXES := nimmari

CLIBS := x_mng cutil X11

include $(TEMPLATES)/ada.mk

