include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(REPOSIT)
ADACTL := true

SUBUNITS := common.check
EXES := c_magic

CLIBS_c_magic=$(UTILS_SLIBS)

include $(TEMPLATES)/ada.mk

