include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk
include $(HOME)/Makefiles/units.mk

ADAVIEW := $(REPOSIT)

EXES := $(UNITS)

CLIBS_servprio := cutil

include $(TEMPLATES)/ada.mk

