include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk
include $(HOME)/Makefiles/units.mk

ADAVIEW := $(REPOSIT)
ADACTL := true

EXES := $(UNITS)

CLIBS := $(UTILS_SLIBS)

include $(TEMPLATES)/ada.mk

