include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(REPOSIT)
ADACTL := true

EXES := pexec pexec.stat

CLIBS := $(UTILS_SLIBS)

LARGS_pexec.stat := $(UTILS_ALIBS)

include $(TEMPLATES)/ada.mk

