include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(USR)/mapcode $(REPOSIT)
ADACTL := true

AFPX := true
AFPX_XREF := afpx_xref

EXES := gc hp_gc

CLIBS := $(UTILS_SLIBS)
CLIBS_gc := $(PCRE_SLIBS) $(X11_SLIBS)

include $(TEMPLATES)/ada.mk

