#!/bin/bash
#set -vx
if [ "$1" = "" ] ; then
  echo "Usage: `basename $0` <scenario>"
  exit 1
fi
export SCENARIO=$1

# For each line
while IFS=' ' read -r from to heading distance ; do
  if [[ $from =~ ^#|^$ ]] ; then
     continue
  fi
  if [ "$from" = "" ] ; then
    break
  fi
  # Do test and save exit status
  export result=`gc $from $to`
  export code=$?
  # Check exit status
  if [ $code -ne 0 ] ; then
    echo "Error: gc exited with code $code"
    exit 1
  fi
  # Check that result is expected
  result=`echo $result | awk '{print $2 " " $4}'`
  expected=$heading" "$distance
  if [ "$result" = "$expected" ] ; then
    echo "From $from to $to -> H=$heading for ${distance}Nm"
  else
    echo "Error: From $from to $to expected $expected != got $result"
    exit 1
  fi
  let L=$L+1
done <$SCENARIO
echo OK.
exit 0

