#!/bin/bash

function error {
  echo "ERROR: " $1 "." 1>&2
  exit 1
}

# Play gc scenario
./player Scenario
ret=$?
if [ $ret -ne 0 ] ; then
  exit 1
fi

# Some hp_gc tests
echo "hp_gc"
function t_hp_gc {
  if [ $# -eq 3 ] ; then
    res="`hp_gc $1 $2`"
    exp="$3"
  elif [ $# -eq 5 ] ; then
    res="`hp_gc $1 $2 $3 $4`"
    exp="$5"
  else
    error "Invalid arguments"
  fi
  ret=$?
  if [ $ret -ne 0 ] ; then
    error "hp_gc has exited with code $ret"
  fi
  if [ "$res" != "$exp" ] ; then
    error "hp_gc $1 $2 $3 $4 has returned $res instead of $exp"
  fi
  echo "hp_gc $1 $2 $3 $4"
  echo " -> $res"
}

# High preocision
# New York -> Melbourne
t_hp_gc 40.786251000 -73.961418000 -37.827455000 145.045353500 \
  "H:  262.731751000, D: 9001Nm 16671km."
t_hp_gc S93HM.RVB8 AU-VIC:KJ.HX5 "H:  262.731751000, D: 9001Nm 16671km."
# One mapcode precision digit in each direction
t_hp_gc FRA:FTGC.R3T-K3 FRA:FTGC.R3T-K4 \
  "H:   89.999999000, D: 0Nm 0km 0m 247mm."
t_hp_gc FRA:FTGC.R3T-K3 FRA:FTGC.R3T-K2 \
  "H:  270.000001000, D: 0Nm 0km 0m 247mm."
t_hp_gc FRA:FTGC.R3T-K3 FRA:FTGC.R3T-DW \
  "H:  179.994819000, D: 0Nm 0km 0m 271mm."
t_hp_gc FRA:FTGC.R3T-K3 FRA:FTGC.R3T-K9 \
  "H:    0.000000000, D: 0Nm 0km 0m 271mm."
# Fonsorbes -> Acuncagua
t_hp_gc FRA:FTGC.R3T-1N 79GMS.VQFW-7R \
  "H:  234.076573000, D: 6010Nm 11131km."
# Comparisons
# Fonsorbes -> Acuncagua
t_hp_gc FRA:FTGC.R3T 79GMS.VQDX  "H:  234.076599000, D: 6010Nm 11131km."
t_hp_gc 43.5318 001.2354 -32.6532 -070.0108 \
  "H:  234.076574000, D: 6010Nm 11131km."
# New York <-> Melbourne
t_hp_gc 40.784758117 -73.963754417 -37.820099500 144.983584217 \
  "H:  262.772168000, D: 9004Nm 16675km."
t_hp_gc US-NJ:Y0.XJ1-KL AU-VIC:PM.N3-8N "H:  262.772168000, D: 9004Nm 16675km."
t_hp_gc -37.820099500 144.983584217 40.784758117 -73.963754417 \
  "H:   71.970595000, D: 9004Nm 16675km."
t_hp_gc AU-VIC:PM.N3-8N US-NJ:Y0.XJ1-KL "H:   71.970595000, D: 9004Nm 16675km."

echo "OK."
