include $(if $(MAKFILES_DIR), $(MAKFILES_DIR), $(HOME)/Makefiles)/common.mk

ADAVIEW := $(REPOSIT)

SUBUNITS := screen-get_event
EXES := land_lem

CLIBS := $(X11_SLIBS)

TXT := Lem
DOCOPTS_Lem := -a toc

include $(TEMPLATES)/ada.mk

